import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerWrap: {
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    marginBottom: 4,
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  headerDecorCircleLarge: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    top: -24,
    right: -20,
  },
  headerDecorCircleSmall: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    bottom: 18,
    left: 18,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  leftSection: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginLeft: -8,
  },
  titleContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#7C3AED',
    fontWeight: '600',
    marginTop: 4,
    opacity: 0.85,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  // Overview Card
  overviewCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  billTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  billTitleText: {
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    flex: 1,
    marginRight: 8,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
  },
  billDateText: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 14,
  },
  totalAmountSection: {
    backgroundColor: '#F5F3FF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#DDD6FE',
  },
  totalLabel: {
    fontSize: 13,
    color: PASTEL_PALETTE.subtitle,
    fontWeight: '600',
    marginBottom: 4,
  },
  totalValue: {
    fontSize: 26,
    fontWeight: '900',
    color: PASTEL_PALETTE.accentDeep,
  },
  noteBox: {
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  noteLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
    marginBottom: 4,
  },
  noteText: {
    fontSize: 14,
    color: PASTEL_PALETTE.title,
  },
  // Progress
  progressSection: {
    marginTop: 6,
  },
  progressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  progressLabel: {
    fontSize: 13,
    color: PASTEL_PALETTE.subtitle,
    fontWeight: '600',
  },
  progressCount: {
    fontSize: 13,
    color: PASTEL_PALETTE.title,
    fontWeight: '700',
  },
  track: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    overflow: 'hidden',
  },
  fill: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 4,
  },
  // Creator Card
  creatorCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  creatorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EDE9FE',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  creatorAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  creatorAvatarText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.accentDeep,
  },
  creatorInfo: {
    flex: 1,
  },
  creatorRoleText: {
    fontSize: 11,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  creatorName: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  creatorEmail: {
    fontSize: 12,
    color: PASTEL_PALETTE.subtitle,
  },
  // Members Card
  membersCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  membersTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 14,
  },
  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    overflow: 'hidden',
  },
  memberAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  memberAvatarText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.subtitle,
  },
  memberInfo: {
    flex: 1,
  },
  memberName: {
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  memberSubtext: {
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    marginTop: 1,
  },
  memberAmountSection: {
    alignItems: 'flex-end',
  },
  memberAmountText: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 4,
  },
  memberStatusPaid: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  memberStatusPaidText: {
    fontSize: 11,
    color: '#059669',
    fontWeight: '700',
  },
  memberStatusPending: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  memberStatusPendingText: {
    fontSize: 11,
    color: '#D97706',
    fontWeight: '700',
  },
  remindBtn: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EDE9FE',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  remindBtnText: {
    fontSize: 11,
    color: PASTEL_PALETTE.accentDeep,
    fontWeight: '700',
  },
  // Pay Sticky Footer
  payFooter: {
    padding: 20,
    paddingBottom: 36,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
  },
  payFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  payFooterLabel: {
    fontSize: 14,
    color: PASTEL_PALETTE.subtitle,
    fontWeight: '600',
  },
  payFooterAmount: {
    fontSize: 22,
    fontWeight: '900',
    color: PASTEL_PALETTE.accentDeep,
  },
  payBtn: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  payBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  paidBanner: {
    backgroundColor: '#D1FAE5',
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paidBannerText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#059669',
    flex: 1,
  },
  cancelBillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
    borderColor: '#FECACA',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginTop: 12,
    marginBottom: 20,
  },
  cancelBillButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#EF4444',
  },
  cancelLockedNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 12,
    marginBottom: 20,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 16,
    backgroundColor: '#FFFBEB',
  },
  cancelLockedNoticeText: {
    flex: 1,
    color: '#92400E',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
});
