import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginTop: 16,
    paddingHorizontal: 17,
    paddingTop: 17,
    paddingBottom: 15,
    borderRadius: 22,
    backgroundColor: '#FFFDFC',
    borderWidth: 1,
    borderColor: '#EEE5EF',
    shadowColor: '#6D4AAF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 2,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 0.8, color: '#9A7DB9' },
  title: { marginTop: 3, fontSize: 17, fontWeight: '900', letterSpacing: -0.25, color: '#29202D' },
  viewAll: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, paddingLeft: 9 },
  viewAllText: { fontSize: 12, fontWeight: '800', color: '#7655B4' },
  amountLine: { marginTop: 18 },
  amountStrong: { fontSize: 21, fontWeight: '900', color: '#29202D' },
  amountMuted: { fontSize: 13, fontWeight: '600', color: '#877B89' },
  overallTrack: { height: 9, marginTop: 10, borderRadius: 99, overflow: 'hidden', backgroundColor: '#F0EBF1' },
  overallFill: { height: '100%', borderRadius: 99 },
  remainingRow: { marginTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  remainingLabel: { fontSize: 11, fontWeight: '600', color: '#877B89' },
  remainingValue: { fontSize: 12, fontWeight: '900' },
  riskList: { marginTop: 11, paddingTop: 2, borderTopWidth: 1, borderTopColor: '#F2EBF1' },
  riskRow: { flexDirection: 'row', alignItems: 'center', paddingTop: 12 },
  categoryIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  riskCopy: { flex: 1, minWidth: 0, marginLeft: 11 },
  riskTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  categoryName: { flex: 1, fontSize: 13, fontWeight: '800', color: '#372D3B' },
  percent: { fontSize: 12, fontWeight: '900', fontVariant: ['tabular-nums'] },
  miniTrack: { height: 5, marginTop: 6, borderRadius: 99, overflow: 'hidden', backgroundColor: '#F1ECF2' },
  miniFill: { height: '100%', borderRadius: 99 },
  categoryHint: { marginTop: 4, fontSize: 10, fontWeight: '600', color: '#837585' },
  categoryHintOver: { color: '#C63B58' },
  stateCard: {
    marginHorizontal: 16, marginTop: 16, padding: 15, borderRadius: 20,
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFDFC',
    borderWidth: 1, borderColor: '#EEE5EF',
  },
  stateIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F1EBF8' },
  stateCopy: { flex: 1, minWidth: 0, marginLeft: 11 },
  stateTitle: { fontSize: 14, fontWeight: '900', color: '#332937' },
  stateText: { marginTop: 3, fontSize: 11, lineHeight: 16, color: '#817483' },
  retryButton: { marginLeft: 8, paddingHorizontal: 11, paddingVertical: 8, borderRadius: 10, backgroundColor: '#EFE7F8' },
  retryText: { fontSize: 11, fontWeight: '800', color: '#6D4AAF' },
  emptyCard: {
    marginHorizontal: 16, marginTop: 16, padding: 16, borderRadius: 22,
    backgroundColor: '#FBF8FC', borderWidth: 1, borderColor: '#EDE4EE',
  },
  emptyTopRow: { flexDirection: 'row', alignItems: 'center' },
  emptyIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEE7F7' },
  emptyAction: {
    marginTop: 14, height: 42, borderRadius: 13, flexDirection: 'row', alignItems: 'center',
    justifyContent: 'center', gap: 7, backgroundColor: '#F0E9F8',
  },
  emptyActionText: { fontSize: 13, fontWeight: '900', color: '#6D4AAF' },
  skeletonCard: {
    marginHorizontal: 16, marginTop: 16, height: 222, padding: 17, borderRadius: 22,
    backgroundColor: '#F7F1F6', borderWidth: 1, borderColor: '#EEE5EF',
  },
  skeletonTitle: { width: '48%', height: 14, borderRadius: 7, backgroundColor: '#E8DFE7' },
  skeletonValue: { width: '62%', height: 24, marginTop: 22, borderRadius: 8, backgroundColor: '#E8DFE7' },
  skeletonTrack: { width: '100%', height: 9, marginTop: 13, borderRadius: 9, backgroundColor: '#E8DFE7' },
  skeletonRow: { width: '100%', height: 38, marginTop: 22, borderRadius: 12, backgroundColor: '#ECE4EB' },
  skeletonRowShort: { width: '78%', height: 38, marginTop: 10, borderRadius: 12, backgroundColor: '#ECE4EB' },
})
