import { StyleSheet, Platform } from 'react-native';
import Colors from '../../../shared/constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background, // Sắc trắng xám sang trọng đặc trưng
  },
  bgCircle: {
    position: 'absolute',
    borderRadius: 200,
    opacity: 0.12, // Tăng nhẹ độ đậm để nổi bật trên nền xám nhẹ
  },
  circleTopLeft: {
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: Colors.primary,
    top: -90,
    left: -90,
  },
  circleMiddleRight: {
    width: 380,
    height: 380,
    borderRadius: 190,
    backgroundColor: Colors.secondary,
    bottom: -110,
    right: -110,
  },
  circleMiddleLeft: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#06B6D4',
    top: '35%',
    left: -130,
    opacity: 0.08,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: Colors.textMuted,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
    paddingHorizontal: 16,
  },

  // Wallet Card Styles
  walletCardContainer: {
    width: '100%',
    marginBottom: 32,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  walletBody: {
    borderRadius: 24,
    padding: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    minHeight: 185,
    position: 'relative',
  },
  walletStitchBorder: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderStyle: 'dashed',
    borderRadius: 22,
    margin: 5,
  },
  walletSlit: {
    position: 'absolute',
    top: 12,
    left: '5%',
    width: '90%',
    height: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.15)',
  },
  walletFlap: {
    position: 'absolute',
    top: 0,
    alignSelf: 'center',
    width: '55%',
    height: 50,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderTopWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  walletFlapStitch: {
    position: 'absolute',
    top: 0,
    left: 4,
    right: 4,
    bottom: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    borderStyle: 'dashed',
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderTopWidth: 0,
  },
  snapButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
    zIndex: 2,
    backgroundColor: '#F59E0B',
    borderColor: '#D97706',
    borderWidth: 2,
  },
  snapButtonInner: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  snapDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: 38,
    marginBottom: 12,
  },
  walletName: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.white,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  cardNumber: {
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: 'rgba(255, 255, 255, 0.95)',
    fontWeight: 'bold',
    marginTop: 4,
    letterSpacing: 1.5,
  },
  goldFoilBadge: {
    backgroundColor: 'rgba(251, 191, 36, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.5)',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  goldFoilText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#FBBF24',
    letterSpacing: 1,
  },
  balanceSection: {
    marginTop: 10,
  },
  balanceLabel: {
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  balanceValue: {
    fontSize: 22,
    fontWeight: '900',
    color: Colors.white,
    marginTop: 2,
  },

  // Form Styles
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 8,
  },
  lengthBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  lengthBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: '#F9FAFB',
    marginBottom: 24,
  },
  inputActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.white,
  },
  inputError: {
    borderColor: '#EF4444',
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: Colors.text,
  },
  errorText: {
    color: '#EF4444',
    fontSize: 14,
    marginTop: -16,
    marginBottom: 16,
    paddingLeft: 4,
  },
  button: {
    height: 56,
    backgroundColor: Colors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
});
