import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const onboardingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.white,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  stepBadge: {
    alignSelf: 'flex-start',
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 16,
  },
  stepBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: PASTEL_PALETTE.textMuted,
    lineHeight: 21,
    marginBottom: 24,
  },
  cardPreview: {
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    marginBottom: 20,
  },
  cardPreviewLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 8,
  },
  cardPreviewNumber: {
    fontSize: 22,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    letterSpacing: 2,
  },
  pinCellsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginVertical: 32,
  },
  pinCell: {
    width: 46,
    height: 54,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinCellFilled: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  pinCellMark: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: PASTEL_PALETTE.accentDeep,
  },
  keypad: {
    marginTop: 'auto',
    paddingBottom: 24,
    gap: 12,
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
  },
  keypadKey: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  keypadKeyText: {
    fontSize: 26,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  keypadSideKey: {
    width: 76,
    height: 76,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keypadSideKeyText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
    textAlign: 'center',
    lineHeight: 18,
  },
  keypadSideKeyTextDisabled: {
    opacity: 0.45,
  },
  pinHeader: {
    alignItems: 'center',
    paddingTop: 24,
    paddingHorizontal: 8,
  },
  pinTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
    textAlign: 'center',
  },
  pinSubtitle: {
    fontSize: 14,
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
    lineHeight: 21,
    maxWidth: 300,
  },
  pinErrorText: {
    color: '#EF4444',
    textAlign: 'center',
    marginTop: -16,
    marginBottom: 12,
    fontSize: 13,
    fontWeight: '600',
  },
  pinLoadingWrap: {
    alignItems: 'center',
    marginTop: 'auto',
    marginBottom: 48,
  },
})
