import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
    paddingHorizontal: 16,
  },
  centerWrap: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
  },
  cardInner: {
    margin: 2,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderRadius: 22,
    padding: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  checkWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  headerSub: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  amountBlock: {
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 14,
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  amountLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  amountValue: {
    fontSize: 32,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    letterSpacing: -0.8,
  },
  amountCurrency: {
    fontSize: 20,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
  },
  flowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  flowParty: {
    width: '36%',
    alignItems: 'center',
    gap: 6,
  },
  flowLogo: {
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  flowIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flowName: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
  },
  brandSmart: {
    color: PASTEL_PALETTE.textMuted,
  },
  brandSpend: {
    color: PASTEL_PALETTE.accentDeep,
  },
  flowArrowWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  flowDash: {
    flex: 1,
    height: 1.5,
    backgroundColor: PASTEL_PALETTE.border,
  },
  flowArrowBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoList: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    gap: 12,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  infoLabel: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '500',
  },
  infoValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginLeft: 16,
  },
  footer: {
    paddingTop: 16,
  },
  btnPrimary: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
    marginBottom: 12,
  },
  btnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '800',
  },
});
