import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  card: {
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 4,
  },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 17, paddingTop: 17 },
  identityRow: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 11 },
  identityCopy: { flex: 1, minWidth: 0 },
  walletName: { fontSize: 15, fontWeight: '900', color: PASTEL_PALETTE.title },
  walletType: { marginTop: 2, fontSize: 11, fontWeight: '600', color: PASTEL_PALETTE.textMuted },
  activeStatus: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: '#ECFDF5' },
  activeDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#10B981' },
  activeText: { fontSize: 10, fontWeight: '800', color: '#047857' },
  balanceBlock: { marginHorizontal: 17, marginTop: 20 },
  balanceLabel: { fontSize: 11, fontWeight: '700', color: PASTEL_PALETTE.textMuted },
  balanceValue: { marginTop: 4, fontSize: 30, fontWeight: '900', color: '#312E81', letterSpacing: -0.8 },
  accountRow: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 9, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10, backgroundColor: '#F5F3FF' },
  accountLabel: { fontSize: 10, fontWeight: '800', color: PASTEL_PALETTE.textMuted },
  accountNumber: { maxWidth: 180, fontSize: 12, fontWeight: '800', color: '#5B21B6', letterSpacing: 0.5 },
  copyHint: { marginTop: 5, marginLeft: 2, fontSize: 9, fontWeight: '500', color: PASTEL_PALETTE.gray400 },
  limitGrid: { flexDirection: 'row', alignItems: 'stretch', marginHorizontal: 17, marginTop: 18, paddingVertical: 13, borderRadius: 16, backgroundColor: '#FAF7FF' },
  limitCell: { flex: 1, minWidth: 0, paddingHorizontal: 12 },
  limitDivider: { width: StyleSheet.hairlineWidth, backgroundColor: '#DDD6FE' },
  limitLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  limitLabel: { fontSize: 10, fontWeight: '700', color: PASTEL_PALETTE.textMuted },
  limitValue: { marginTop: 6, fontSize: 12, fontWeight: '900', color: PASTEL_PALETTE.title },
  actionsRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 17, paddingHorizontal: 10, paddingTop: 14, paddingBottom: 15, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: PASTEL_PALETTE.border },
  action: { flex: 1, alignItems: 'center' },
  actionIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  actionLabel: { marginTop: 6, fontSize: 10, fontWeight: '800', color: PASTEL_PALETTE.title },
  greenAction: { backgroundColor: '#ECFDF5' },
  greenText: { color: '#059669' },
  orangeAction: { backgroundColor: '#FFF7ED' },
  orangeText: { color: '#EA580C' },
  purpleAction: { backgroundColor: '#F5F3FF' },
  purpleText: { color: '#7C3AED' },
  blueAction: { backgroundColor: '#EFF6FF' },
  blueText: { color: '#2563EB' },
})
