import { StyleSheet } from 'react-native';
import Colors from '../../constants/Colors';
import { PASTEL_PALETTE } from '../../constants/PastelPalette';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 12,
    paddingBottom: 40,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 10,
  },
  dragIndicator: {
    width: 40,
    height: 5,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    marginBottom: 20,
  },
  headerIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    paddingHorizontal: 24,
    marginBottom: 8,
    alignItems: 'center',
    position: 'relative',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: Colors.text,
  },
  closeButton: {
    position: 'absolute',
    right: 24,
    padding: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
  },
  subtitle: {
    fontSize: 15,
    color: Colors.textMuted,
    marginBottom: 32,
    textAlign: 'center',
    paddingHorizontal: 32,
    lineHeight: 22,
  },
  pinContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    gap: 16,
  },
  pinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    backgroundColor: 'transparent',
  },
  pinDotActive: {
    backgroundColor: PASTEL_PALETTE.primary,
    borderColor: PASTEL_PALETTE.primary,
    transform: [{ scale: 1.2 }],
  },
  errorText: {
    color: Colors.error,
    fontSize: 14,
    marginBottom: 16,
  },
  forgotPinText: {
    color: PASTEL_PALETTE.primary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 32,
  },
  keypadContainer: {
    width: '100%',
    paddingHorizontal: 40,
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  key: {
    width: 76,
    height: 76,
    borderRadius: 38,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  keyEmpty: {
    width: 76,
    height: 76,
    backgroundColor: 'transparent',
  },
  keyText: {
    fontSize: 30,
    fontWeight: '400',
    color: '#1F2937',
  },
});
