import { StyleSheet } from "react-native";
import Colors from "../../../../shared/constants/Colors";

export const styles = StyleSheet.create({
  container: {
    position: 'relative',
    marginBottom: 50,
    zIndex: 10,
    elevation: 10,
  },
  headerBackground: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 24,
    paddingBottom: 75,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    top: -50,
    right: -40,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  circle2: {
    position: 'absolute',
    bottom: -60,
    left: -20,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  circle3: {
    position: 'absolute',
    top: 40,
    left: '40%',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  greetingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
    zIndex: 1,
  },
  backButton: {
    marginRight: 14,
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  greetingText: {
    fontSize: 22,
    fontWeight: '700',
    color: Colors.white,
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  subGreetingText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.7)',
  },
  balanceSection: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: "center",
    zIndex: 1,
    marginTop: 10,
  },
  balanceHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  totalBalanceLabel: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
    fontWeight: "600",
    letterSpacing: 1,
  },
  eyeButton: {
    marginLeft: 12,
    padding: 4,
  },
  totalBalanceValue: {
    fontSize: 44,
    fontWeight: "800",
    color: Colors.white,
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  badgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  badgeText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 6,
  },
  statsCard: {
    position: 'absolute',
    bottom: -35,
    left: 20,
    right: 20,
    backgroundColor: Colors.white,
    flexDirection: "row",
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 16,
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 8,
  },
  statGroup: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  statTextGroup: {
    flexDirection: "column",
  },
  statLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 4,
    fontWeight: "500",
  },
  statValueIncome: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.text,
  },
  statValueExpense: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.text,
  },
  divider: {
    width: 1,
    height: 40,
    backgroundColor: Colors.border,
    marginHorizontal: 8,
  },
});
