import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  dashboardHeaderContent: {
    paddingHorizontal: 20,
    paddingBottom: 35,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerEyebrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  dashboardBackBtn: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -6,
    backgroundColor: 'rgba(255,255,255,0.55)',
  },
  headerTextWrap: {
    flex: 1,
  },
  headerMark: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  headerEyebrow: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    color: '#80617D',
  },
  title: {
    fontSize: 20,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  dashboardTitle: {
    marginTop: 10,
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: -0.8,
    color: PASTEL_PALETTE.title,
  },
  dashboardSubtitle: {
    maxWidth: 295,
    marginTop: 3,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  headerCreateBtn: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    shadowColor: '#6D4AAF',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 5,
  },
  body: {
    flex: 1,
  },
  summaryPad: {
    paddingHorizontal: 12,
    marginTop: -25,
    paddingTop: 0,
    zIndex: 2,
  },
  pager: {
    flex: 1,
  },
  page: {
    flex: 1,
  },
  pageListContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 120,
    flexGrow: 1,
  },
  emptyBox: {
    paddingVertical: 36,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '500',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  errorText: {
    marginTop: 40,
    marginHorizontal: 20,
    textAlign: 'center',
    color: '#DC2626',
    fontWeight: '600',
  },
  sectionLabel: {
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  field: {
    marginBottom: 16,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.textDark,
  },
  selectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.textDark,
  },
  selectPlaceholder: {
    color: PASTEL_PALETTE.textMuted,
  },
  periodRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  periodChip: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 10,
    alignItems: 'center',
  },
  periodChipActive: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  periodChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  periodChipTextActive: {
    color: PASTEL_PALETTE.title,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 8,
  },
  dateBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dateBtnDisabled: {
    opacity: 0.7,
    backgroundColor: PASTEL_PALETTE.gray100,
  },
  dateLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  dateValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  hint: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '500',
    color: PASTEL_PALETTE.textMuted,
  },
  errorField: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#DC2626',
  },
  submitBtn: {
    marginTop: 8,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    paddingVertical: 14,
    alignItems: 'center',
  },
  submitBtnDisabled: {
    opacity: 0.55,
  },
  submitText: {
    color: PASTEL_PALETTE.white,
    fontSize: 15,
    fontWeight: '800',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  detailHeaderContent: {
    paddingHorizontal: 18,
    paddingBottom: 37,
  },
  detailHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  detailHeaderBack: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  detailHeaderCopy: { flex: 1, minWidth: 0 },
  detailHeaderEyebrow: { fontSize: 9, fontWeight: '900', letterSpacing: 1, color: '#896B85' },
  detailHeaderTitle: { marginTop: 2, fontSize: 22, fontWeight: '900', letterSpacing: -0.5, color: PASTEL_PALETTE.title },
  detailHeaderSubtitle: { marginTop: 2, fontSize: 10, fontWeight: '600', color: PASTEL_PALETTE.subtitle },
  detailHeaderMark: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.58)',
  },
  detailScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 46,
  },
  detailHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFDFE',
    borderRadius: 21,
    borderWidth: 1,
    borderColor: '#EADFEB',
    padding: 13,
    marginBottom: 10,
    shadowColor: '#72527D',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 13,
    elevation: 3,
  },
  detailIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHeroText: {
    flex: 1,
  },
  detailCategoryName: {
    fontSize: 17,
    fontWeight: '900',
    color: PASTEL_PALETTE.textDark,
  },
  detailGroupName: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
  },
  detailDeletedHint: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '700',
    color: '#DC2626',
  },
  detailStatusBadge: {
    maxWidth: 91,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  detailStatusText: {
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 13,
  },
  detailLimitCard: {
    backgroundColor: '#FFFDFE',
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#EADFEB',
    padding: 15,
    marginBottom: 10,
    shadowColor: '#72527D',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 3,
  },
  detailLimitTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  detailLimitCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailLimitLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  detailLimitValue: {
    marginTop: 2,
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.7,
    color: PASTEL_PALETTE.title,
    fontVariant: ['tabular-nums'],
  },
  detailLimitValueOver: { color: '#C73E63' },
  detailPercentBadge: {
    width: 68,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailPercentValue: { fontSize: 17, fontWeight: '900', fontVariant: ['tabular-nums'] },
  detailPercentLabel: { marginTop: -1, fontSize: 8, fontWeight: '700', color: '#8D7E8F' },
  detailProgressTrack: {
    height: 9,
    marginTop: 13,
    borderRadius: 6,
    backgroundColor: '#EEE8F1',
    overflow: 'hidden',
  },
  detailProgressFill: { height: '100%', borderRadius: 6 },
  detailMoneyStats: {
    marginTop: 12,
    paddingBottom: 12,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EEE5EE',
  },
  detailMoneyStat: { flex: 1 },
  detailMoneyValue: { marginTop: 3, fontSize: 13, fontWeight: '900', color: '#443746', fontVariant: ['tabular-nums'] },
  detailMetaRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  detailMetaItem: {
    flex: 1,
  },
  detailMetaDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: PASTEL_PALETTE.border,
    marginHorizontal: 12,
  },
  detailMetaLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  detailMetaIconRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  detailMetaValue: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  detailSpendSection: {
    backgroundColor: '#FFFDFE',
    borderRadius: 21,
    borderWidth: 1,
    borderColor: '#EADFEB',
    padding: 15,
    marginBottom: 4,
  },
  detailSectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 2 },
  detailSectionIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0EAFE' },
  detailSectionSubtitle: { marginTop: 1, fontSize: 9, fontWeight: '600', color: '#988A99' },
  editLockedCard: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    padding: 14,
    marginBottom: 14,
  },
  editLockedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  editLockedText: {
    flex: 1,
  },
  editLockedLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  editLockedValue: {
    marginTop: 3,
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  editLockedDivider: {
    height: 1,
    backgroundColor: PASTEL_PALETTE.border,
    marginVertical: 12,
  },
  editSection: {
    marginBottom: 16,
  },
  editAmountBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  editAmountBoxError: {
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
  },
  editAmountPrefix: {
    fontSize: 22,
    fontWeight: '900',
    color: PASTEL_PALETTE.lavender,
    marginRight: 8,
  },
  editAmountInput: {
    flex: 1,
    fontSize: 28,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    paddingVertical: 10,
  },
  actionColumn: {
    marginTop: 18,
    gap: 10,
  },
  primaryActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    paddingVertical: 14,
  },
  primaryActionText: {
    color: PASTEL_PALETTE.white,
    fontSize: 15,
    fontWeight: '800',
  },
  dangerOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    paddingVertical: 13,
  },
  dangerOutlineText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#DC2626',
  },
  lockedBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.gray100,
    padding: 14,
    marginBottom: 16,
  },
  lockedTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  lockedValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  secondaryBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 12,
    alignItems: 'center',
  },
  secondaryBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  dangerBtn: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#FEE2E2',
    paddingVertical: 12,
    alignItems: 'center',
  },
  dangerBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#DC2626',
  },
  pickerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  pickerSheet: {
    backgroundColor: PASTEL_PALETTE.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 24,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: PASTEL_PALETTE.border,
  },
  pickerTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  pickerDone: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
})
