import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  headerCreateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerCreateText: {
    color: PASTEL_PALETTE.white,
    fontSize: 13,
    fontWeight: '800',
  },
  body: {
    flex: 1,
  },
  summaryPad: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  pager: {
    flex: 1,
  },
  page: {
    flex: 1,
  },
  pageListContent: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 40,
    flexGrow: 1,
  },
  emptyBox: {
    paddingVertical: 36,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '500',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  errorText: {
    marginTop: 40,
    marginHorizontal: 20,
    textAlign: 'center',
    color: '#DC2626',
    fontWeight: '600',
  },
  sectionLabel: {
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  field: {
    marginBottom: 16,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.textDark,
  },
  selectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.textDark,
  },
  selectPlaceholder: {
    color: PASTEL_PALETTE.textMuted,
  },
  periodRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  periodChip: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 10,
    alignItems: 'center',
  },
  periodChipActive: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  periodChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  periodChipTextActive: {
    color: PASTEL_PALETTE.title,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 8,
  },
  dateBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dateBtnDisabled: {
    opacity: 0.7,
    backgroundColor: PASTEL_PALETTE.gray100,
  },
  dateLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  dateValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  hint: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '500',
    color: PASTEL_PALETTE.textMuted,
  },
  errorField: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#DC2626',
  },
  submitBtn: {
    marginTop: 8,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    paddingVertical: 14,
    alignItems: 'center',
  },
  submitBtnDisabled: {
    opacity: 0.55,
  },
  submitText: {
    color: PASTEL_PALETTE.white,
    fontSize: 15,
    fontWeight: '800',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  detailHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    padding: 14,
    marginBottom: 12,
  },
  detailIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHeroText: {
    flex: 1,
  },
  detailCategoryName: {
    fontSize: 18,
    fontWeight: '900',
    color: PASTEL_PALETTE.textDark,
  },
  detailGroupName: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
  },
  detailDeletedHint: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '700',
    color: '#DC2626',
  },
  detailStatusBadge: {
    maxWidth: 100,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  detailStatusText: {
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 13,
  },
  detailLimitCard: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    padding: 16,
    marginBottom: 12,
  },
  detailLimitLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  detailLimitValue: {
    marginTop: 4,
    fontSize: 28,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  detailMetaRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  detailMetaItem: {
    flex: 1,
  },
  detailMetaDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: PASTEL_PALETTE.border,
    marginHorizontal: 12,
  },
  detailMetaLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  detailMetaValue: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  detailSpendSection: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    padding: 14,
    marginBottom: 4,
  },
  editLockedCard: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    padding: 14,
    marginBottom: 14,
  },
  editLockedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  editLockedText: {
    flex: 1,
  },
  editLockedLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  editLockedValue: {
    marginTop: 3,
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  editLockedDivider: {
    height: 1,
    backgroundColor: PASTEL_PALETTE.border,
    marginVertical: 12,
  },
  editSection: {
    marginBottom: 16,
  },
  editAmountBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  editAmountBoxError: {
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
  },
  editAmountPrefix: {
    fontSize: 22,
    fontWeight: '900',
    color: PASTEL_PALETTE.lavender,
    marginRight: 8,
  },
  editAmountInput: {
    flex: 1,
    fontSize: 28,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    paddingVertical: 10,
  },
  actionColumn: {
    marginTop: 18,
    gap: 10,
  },
  primaryActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    paddingVertical: 14,
  },
  primaryActionText: {
    color: PASTEL_PALETTE.white,
    fontSize: 15,
    fontWeight: '800',
  },
  dangerOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    paddingVertical: 13,
  },
  dangerOutlineText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#DC2626',
  },
  lockedBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.gray100,
    padding: 14,
    marginBottom: 16,
  },
  lockedTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  lockedValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  secondaryBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 12,
    alignItems: 'center',
  },
  secondaryBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  dangerBtn: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#FEE2E2',
    paddingVertical: 12,
    alignItems: 'center',
  },
  dangerBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#DC2626',
  },
  pickerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  pickerSheet: {
    backgroundColor: PASTEL_PALETTE.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 24,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: PASTEL_PALETTE.border,
  },
  pickerTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  pickerDone: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
})
