import { StyleSheet, Dimensions } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

const PRIMARY = PASTEL_PALETTE.accentDeep
const PRIMARY_LIGHT = PASTEL_PALETTE.accentSoft
const PRIMARY_DARK = PASTEL_PALETTE.title

export const PIE_PAGE_WIDTH = Dimensions.get('window').width - 40

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 8,
  },
  loadingWrap: {
    paddingVertical: 48,
    alignItems: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 20,
    padding: 4,
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  toggleButtonActive: {
    backgroundColor: PASTEL_PALETTE.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginLeft: 6,
  },
  toggleTextActive: {
    color: PRIMARY,
  },
  dateSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  dateNavBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  dateTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  dateText: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginLeft: 8,
  },
  periodChips: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 16,
  },
  periodChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  periodChipActive: {
    backgroundColor: PRIMARY_LIGHT,
    borderColor: PRIMARY,
  },
  periodChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  periodChipTextActive: {
    color: PRIMARY_DARK,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  summaryCard: {
    width: '48%',
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  summaryCardActive: {
    borderColor: PRIMARY,
    backgroundColor: '#FDF2F8',
  },
  summaryLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
    color: PASTEL_PALETTE.textMuted,
  },
  summaryLabelActive: {
    color: PRIMARY,
  },
  summaryValue: {
    fontSize: 17,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  chartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
    minHeight: 220,
  },
  donutContainer: {
    width: 248,
    height: 248,
    borderRadius: 124,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  donutCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    maxWidth: 112,
  },
  donutCenterHint: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 2,
  },
  donutCenterTotal: {
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
  },
  donutCenterTap: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
  },
  donutCenterIcon: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  donutCenterPct: {
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  donutCenterName: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
    lineHeight: 14,
  },
  donutCenterDeleted: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
  },
  pieChartWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  categoryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: PRIMARY,
  },
  categorySwipeHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  categorySwipeHintText: {
    fontSize: 12,
    fontWeight: '600',
    color: PRIMARY,
  },
  categoryScrollContent: {
    paddingHorizontal: 4,
    paddingBottom: 4,
  },
  categoryCard: {
    alignItems: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    marginRight: 8,
  },
  categoryCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  categoryCardPct: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  categoryCardName: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
    lineHeight: 14,
    minHeight: 28,
  },
  categoryCardDeleted: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
  },
  categoryCardAmount: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
  },
  lineChartWrapper: {
    width: '100%',
    alignItems: 'stretch',
    minHeight: 260,
  },
  lineChartLegend: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 4,
    flexWrap: 'wrap',
    gap: 12,
  },
  dualLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  lineTrendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  lineChartLegendText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  lineChartHint: {
    fontSize: 11,
    color: PASTEL_PALETTE.textMuted,
    marginLeft: 'auto',
  },
  fixedValueBanner: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
    minHeight: 64,
    justifyContent: 'center',
  },
  fixedValueDay: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  fixedValueRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  fixedValueText: {
    fontSize: 15,
    fontWeight: '800',
  },
  fixedValueHint: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
  },
  lineChartPanel: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingTop: 8,
    paddingBottom: 12,
  },
  lineChartScroll: {
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  pointerLabel: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dualPointerLabel: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 120,
    gap: 4,
  },
  pointerLabelText: {
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  yAxisLabel: {
    color: PASTEL_PALETTE.textMuted,
    fontSize: 12,
  },
  emptyChartText: {
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
    paddingHorizontal: 24,
    fontWeight: '600',
  },
  pickerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  pickerSheet: {
    backgroundColor: PASTEL_PALETTE.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: 32,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 12,
    marginBottom: 12,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: PASTEL_PALETTE.title,
  },
  pickerDone: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.accentDeep,
  },
})
