import { StyleSheet } from "react-native";
import Colors from "../../../../shared/constants/Colors";
import { PASTEL_PALETTE } from "../../../../shared/constants/PastelPalette";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerShell: {
    paddingBottom: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: -8,
  },
  headerSpacer: {
    width: 40,
  },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: "900",
    color: PASTEL_PALETTE.title,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  scrollContent: {
    paddingBottom: 40,
    paddingTop: 16,
  },
  cardContainer: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 4,
    marginBottom: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  segmentWrap: {
    paddingHorizontal: 0,
  },
  segmentContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.55)",
    borderRadius: 100,
    padding: 5,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.75)",
  },
  segment: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 11,
    borderRadius: 100,
    gap: 6,
  },
  segmentActive: {
    backgroundColor: Colors.white,
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  segmentText: {
    fontSize: 15,
    fontWeight: "700",
    color: PASTEL_PALETTE.subtitle,
  },
  segmentTextActive: {
    color: PASTEL_PALETTE.accentDeep,
  },
  formContent: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: PASTEL_PALETTE.title,
    marginBottom: 12,
  },
  walletGroupContainer: {
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 20,
    paddingVertical: 16,
    marginBottom: 24,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  walletCardScroll: {
    marginHorizontal: -16,
    paddingBottom: 16,
  },
  walletCardContent: {
    paddingHorizontal: 16,
  },
  walletCard: {
    minWidth: 170,
    height: 82,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    marginRight: 12,
    padding: 12,
    paddingRight: 24,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.white,
  },
  walletCardActive: {
    borderColor: PASTEL_PALETTE.accent,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  brandLogo: {
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.85)",
  },
  walletIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  walletInfo: {
    flex: 1,
  },
  walletBrandName: {
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  brandSmart: {
    color: PASTEL_PALETTE.title,
  },
  brandSpend: {
    color: PASTEL_PALETTE.accent,
  },
  walletName: {
    fontSize: 14,
    fontWeight: "700",
    color: PASTEL_PALETTE.title,
    marginBottom: 4,
  },
  walletBalance: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: "600",
  },
  amountContainer: {
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 18,
    padding: 18,
    marginTop: 8,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  amountLabel: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 8,
    fontWeight: "600",
  },
  amountInputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
  },
  amountInput: {
    flex: 1,
    fontSize: 32,
    fontWeight: "700",
    color: PASTEL_PALETTE.title,
    padding: 0,
    margin: 0,
  },
  currencySymbol: {
    fontSize: 24,
    fontWeight: "600",
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
    marginLeft: 4,
  },
  suggestionContainer: {
    flexDirection: "row",
    marginTop: 16,
    paddingHorizontal: 16,
    gap: 8,
  },
  suggestionChip: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 100,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  suggestionText: {
    fontSize: 13,
    color: PASTEL_PALETTE.accentDeep,
    fontWeight: "700",
  },
  bannerContainer: {
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    borderRadius: 16,
    padding: 14,
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  bannerText: {
    flex: 1,
    fontSize: 13,
    color: PASTEL_PALETTE.subtitle,
    lineHeight: 18,
    fontWeight: "500",
  },
  sourceContainer: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  sourceOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  sourceOptionActive: {
    borderColor: PASTEL_PALETTE.accent,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  sourceIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  sourceInfo: {
    flex: 1,
  },
  sourceTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: PASTEL_PALETTE.title,
    marginBottom: 2,
  },
  sourceSubtitle: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: PASTEL_PALETTE.border,
    justifyContent: "center",
    alignItems: "center",
  },
  radioOuterActive: {
    borderColor: PASTEL_PALETTE.accentDeep,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: PASTEL_PALETTE.accentDeep,
  },
  securityContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PASTEL_PALETTE.accentSoft,
    padding: 16,
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  securityIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.white,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  securityInfo: {
    flex: 1,
  },
  securityText: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    lineHeight: 18,
    marginBottom: 4,
  },
  securityLink: {
    fontSize: 13,
    fontWeight: "600",
    color: PASTEL_PALETTE.accentDeep,
  },
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "transparent",
  },
  confirmButton: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 18,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  confirmButtonDisabled: {
    backgroundColor: Colors.border,
    shadowOpacity: 0,
    elevation: 0,
  },
  confirmButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: "700",
  },
  confirmButtonTextDisabled: {
    color: PASTEL_PALETTE.textMuted,
  },
  bankLinkCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: "dashed",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  bankLinkIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.border + "55",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  bankLinkInfo: {
    flex: 1,
    minWidth: 0,
  },
  bankLinkTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.text,
  },
  bankLinkHint: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 8,
    lineHeight: 18,
  },
});
