import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Button, Empty, Form, Input, Modal, Progress, Select, Skeleton, Table, Tag, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { AlertOutlined, CheckOutlined, ControlOutlined, DownloadOutlined, FileProtectOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { apiClient } from '../../services/api';
import './ControlCenter.css';

type Row = Record<string, unknown> & { id?: number };
type View = 'transactions' | 'cases' | 'alerts' | 'reports';
const cash = (v: unknown) => `${Number(v || 0).toLocaleString('vi-VN')} ₫`;
const when = (v: unknown) => v ? dayjs(String(v)).format('DD/MM/YYYY HH:mm') : '—';
const statusColor = (v: unknown) => v === 'SUCCESS' || v === 'RESOLVED' ? 'success' : v === 'FAILED' || v === 'CRITICAL' ? 'error' : v === 'HIGH' ? 'volcano' : 'processing';

const config = {
  transactions: { eyebrow: 'Dòng tiền', title: 'Trung tâm giao dịch', description: 'Giám sát nạp, rút, chuyển tiền và mọi trạng thái xử lý trong một luồng.', icon: <ControlOutlined /> },
  cases: { eyebrow: 'Kiểm soát sự cố', title: 'Hồ sơ điều tra', description: 'Ghi nhận, theo dõi và đóng sự cố tài chính với lý do rõ ràng.', icon: <FileProtectOutlined /> },
  alerts: { eyebrow: 'Giám sát chủ động', title: 'Cảnh báo rủi ro', description: 'Phát hiện số dư âm, giao dịch treo và lỗi phát sinh trong ngày.', icon: <AlertOutlined /> },
  reports: { eyebrow: 'Phân tích tài chính', title: 'Báo cáo vận hành', description: 'Tổng hợp số dư, khối lượng và chất lượng giao dịch toàn hệ thống.', icon: <DownloadOutlined /> },
};

export function ControlCenterPage({ view }: { view: View }) {
  const [data, setData] = useState<Record<string, unknown> | Row[] | null>(null);
  const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [createOpen, setCreateOpen] = useState(false); const [resolve, setResolve] = useState<Row | null>(null);
  const [form] = Form.useForm(); const [resolveForm] = Form.useForm();
  const endpoint = view === 'transactions' ? '/transactions' : view === 'reports' ? '/reports' : view === 'alerts' ? '/alerts' : '/cases';
  const load = useCallback(async () => { setLoading(true); try { const response = await apiClient.get(`/api/v1/admin/control-center${endpoint}`); setData(response.data?.data); } catch { message.error('Không tải được dữ liệu kiểm soát'); } finally { setLoading(false); } }, [endpoint]);
  // Initial route synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const source = useMemo(() => { const rows = Array.isArray(data) ? data : ((data?.items as Row[]) || []); const q = query.trim().toLowerCase(); return rows.filter(r => !q || Object.values(r).some(v => String(v ?? '').toLowerCase().includes(q))); }, [data, query]);
  const createCase = async (values: Record<string,string>) => { try { await apiClient.post('/api/v1/admin/control-center/cases', values); message.success('Đã mở hồ sơ điều tra'); setCreateOpen(false); form.resetFields(); await load(); } catch { message.error('Không thể tạo hồ sơ'); } };
  const resolveCase = async (values: { resolutionNote: string }) => { try { await apiClient.put(`/api/v1/admin/control-center/cases/${resolve?.id}/resolve`, values); message.success('Đã đóng hồ sơ'); setResolve(null); resolveForm.resetFields(); await load(); } catch { message.error('Không thể đóng hồ sơ'); } };
  const exportCsv = () => { const rows = source; if (!rows.length) return message.info('Không có dữ liệu để xuất'); const keys = Object.keys(rows[0]); const csv = [keys.join(','), ...rows.map(r => keys.map(k => `"${String(r[k] ?? '').replaceAll('"','""')}"`).join(','))].join('\n'); const url = URL.createObjectURL(new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `smartspend-${view}-${dayjs().format('YYYYMMDD-HHmm')}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  const meta = config[view];
  return <main className="control-page"><header className="control-hero"><div className="control-icon">{meta.icon}</div><div><span>{meta.eyebrow}</span><h2>{meta.title}</h2><p>{meta.description}</p></div><Button icon={<ReloadOutlined />} loading={loading} onClick={() => void load()}>Làm mới</Button></header>{view === 'reports' ? <ReportView data={data as Record<string,unknown> | null} loading={loading} exportCsv={exportCsv} /> : <><section className="control-summary"><Metric label="Tổng bản ghi" value={source.length} /><Metric label={view === 'transactions' ? 'Đang chờ' : 'Mức cao / mở'} value={view === 'transactions' ? Number((data as Record<string,unknown>)?.pending || 0) : source.filter(r => r.status === 'OPEN' || r.severity === 'HIGH').length} /><Metric label={view === 'transactions' ? 'Thất bại' : 'Nghiêm trọng'} value={view === 'transactions' ? Number((data as Record<string,unknown>)?.failed || 0) : source.filter(r => r.severity === 'CRITICAL').length} danger /></section><section className="control-table"><div className="control-toolbar"><Input allowClear placeholder="Tìm mã giao dịch, người dùng, trạng thái..." value={query} onChange={e => setQuery(e.target.value)} /> <div>{view === 'cases' && <Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateOpen(true)}>Mở hồ sơ</Button>}<Button icon={<DownloadOutlined />} onClick={exportCsv}>Xuất CSV</Button></div></div>{loading ? <Skeleton active paragraph={{ rows: 10 }} /> : <Table rowKey={(r) => String(r.id ?? r.transactionCode ?? r.reference)} columns={columns(view, setResolve)} dataSource={source} scroll={{ x: 1050 }} pagination={{ pageSize: 15, showSizeChanger: false }} locale={{ emptyText: <Empty description="Không có dữ liệu" /> }} />}</section></>}
  <Modal title="Mở hồ sơ điều tra" open={createOpen} onCancel={() => setCreateOpen(false)} footer={null} destroyOnClose><Form form={form} layout="vertical" onFinish={createCase}><Form.Item name="transactionCode" label="Mã giao dịch"><Input maxLength={100} /></Form.Item><Form.Item name="severity" label="Mức độ" rules={[{required:true}]}><Select options={['CRITICAL','HIGH','MEDIUM','LOW'].map(v=>({value:v,label:v}))} /></Form.Item><Form.Item name="title" label="Tiêu đề" rules={[{required:true}]}><Input maxLength={180} /></Form.Item><Form.Item name="description" label="Mô tả điều tra" rules={[{required:true,min:10}]}><Input.TextArea rows={4} maxLength={1000} showCount /></Form.Item><Button block type="primary" htmlType="submit">Tạo hồ sơ</Button></Form></Modal>
  <Modal title="Đóng hồ sơ sự cố" open={!!resolve} onCancel={() => setResolve(null)} footer={null} destroyOnClose><Alert type="warning" showIcon message="Hành động được ghi vào nhật ký quản trị" /><Form form={resolveForm} layout="vertical" onFinish={resolveCase}><Form.Item name="resolutionNote" label="Kết quả xử lý" rules={[{required:true,min:10}]}><Input.TextArea rows={5} maxLength={1000} showCount /></Form.Item><Button block type="primary" icon={<CheckOutlined />} htmlType="submit">Xác nhận đã xử lý</Button></Form></Modal></main>;
}

function Metric({ label, value, danger=false }: { label:string; value:number; danger?:boolean }) { return <div><span>{label}</span><strong className={danger && value ? 'danger' : ''}>{value.toLocaleString('vi-VN')}</strong></div>; }
function columns(view: View, setResolve: (row: Row)=>void): ColumnsType<Row> { if(view === 'transactions') return [{title:'Mã',dataIndex:'transactionCode',render:v=><code>{String(v)}</code>},{title:'Người dùng',render:(_,r)=><div className="control-person"><strong>{String(r.username)}</strong><span>{String(r.email)}</span></div>},{title:'Loại',dataIndex:'type',render:v=><Tag>{String(v)}</Tag>},{title:'Số tiền',dataIndex:'amount',align:'right',render:v=><strong>{cash(v)}</strong>},{title:'Trạng thái',dataIndex:'status',render:v=><Tag color={statusColor(v)}>{String(v)}</Tag>},{title:'Thời gian',dataIndex:'createdAt',render:when}]; if(view==='cases') return [{title:'Mức độ',dataIndex:'severity',render:v=><Tag color={statusColor(v)}>{String(v)}</Tag>},{title:'Hồ sơ',render:(_,r)=><div className="control-person"><strong>{String(r.title)}</strong><span>{String(r.transactionCode ?? 'Không gắn giao dịch')}</span></div>},{title:'Trạng thái',dataIndex:'status',render:v=><Tag color={statusColor(v)}>{String(v)}</Tag>},{title:'Người tạo',dataIndex:'createdBy'},{title:'Ngày tạo',dataIndex:'createdAt',render:when},{title:'',render:(_,r)=>r.status==='OPEN'?<Button type="link" onClick={()=>setResolve(r)}>Đóng hồ sơ</Button>:null}]; return [{title:'Mức độ',dataIndex:'severity',render:v=><Tag color={statusColor(v)}>{String(v)}</Tag>},{title:'Cảnh báo',render:(_,r)=><div className="control-person"><strong>{String(r.title)}</strong><span>{String(r.type)}</span></div>},{title:'Tham chiếu',dataIndex:'reference',render:v=><code>{String(v)}</code>},{title:'Giá trị',dataIndex:'amount',align:'right',render:cash}]; }
function ReportView({data,loading,exportCsv}:{data:Record<string,unknown>|null;loading:boolean;exportCsv:()=>void}) { if(loading)return <Skeleton active paragraph={{rows:12}}/>; const byType=(data?.volumeByType||{}) as Record<string,number>; const max=Math.max(1,...Object.values(byType).map(Number)); return <><section className="control-summary"><Metric label="Số giao dịch" value={Number(data?.transactionCount||0)}/><Metric label="Thành công" value={Number(data?.successCount||0)}/><Metric label="Thất bại" value={Number(data?.failedCount||0)} danger/></section><section className="report-grid"><div className="report-balance"><span>Tổng số dư hệ thống</span><strong>{cash(data?.walletBalance)}</strong><p>Dữ liệu tại {when(data?.generatedAt)}</p><Button icon={<DownloadOutlined/>} onClick={exportCsv}>Xuất dữ liệu</Button></div><div className="report-types"><h3>Khối lượng theo loại</h3>{Object.entries(byType).map(([key,value])=><div key={key}><span>{key}<b>{cash(value)}</b></span><Progress percent={Math.round(Number(value)/max*100)} showInfo={false}/></div>)}</div></section></>; }
