import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '../../shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  scrollContent: {
    paddingBottom: 40,
  },

  // Header
  headerContent: {
    paddingBottom: 28,
  },
  headerTop: {
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
  },
  avatarContainer: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarText: {
    color: PASTEL_PALETTE.white,
    fontSize: 22,
    fontWeight: '800',
  },
  userInfo: {
    flex: 1,
  },
  userNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  userName: {
    color: PASTEL_PALETTE.title,
    fontSize: 17,
    fontWeight: '800',
    flexShrink: 1,
  },
  userEmail: {
    color: PASTEL_PALETTE.subtitle,
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 2,
  },
  userStk: {
    color: PASTEL_PALETTE.textMuted,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  badgeText: {
    color: PASTEL_PALETTE.accentDeep,
    fontSize: 11,
    fontWeight: '700',
  },
  editBtn: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },

  // Profile detail modal
  profileModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  profileModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  profileModalSheet: {
    backgroundColor: PASTEL_PALETTE.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 10,
    paddingHorizontal: 16,
    maxHeight: '88%',
  },
  profileModalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.border,
    marginBottom: 12,
  },
  profileModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  profileModalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  profileModalClose: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileModalLoading: {
    paddingVertical: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileModalHero: {
    alignItems: 'center',
    paddingVertical: 18,
  },
  profileModalAvatar: {
    width: 80,
    height: 80,
    borderRadius: 24,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileModalAvatarWrap: {
    width: 80,
    height: 80,
    marginBottom: 8,
  },
  profileModalAvatarImage: {
    width: 80,
    height: 80,
    borderRadius: 24,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  profileModalAvatarBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: PASTEL_PALETTE.bg,
  },
  profileModalChangeHint: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 10,
  },
  profileModalAvatarText: {
    color: PASTEL_PALETTE.white,
    fontSize: 28,
    fontWeight: '800',
  },
  profileModalNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  profileModalName: {
    fontSize: 20,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  profileModalCard: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    overflow: 'hidden',
    marginBottom: 12,
  },
  profileInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PASTEL_PALETTE.border,
  },
  profileInfoRowLast: {
    borderBottomWidth: 0,
  },
  profileInfoIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  profileInfoContent: {
    flex: 1,
  },
  profileInfoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 2,
  },
  profileInfoValue: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },

  // Quick actions
  quickActionsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginTop: -18,
    gap: 10,
    marginBottom: 8,
  },
  quickActionCard: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  quickActionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    flex: 1,
    marginRight: 8,
  },
  iconBox: {
    width: 34,
    height: 34,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBoxPink: {
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  iconBoxLavender: {
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
  },
  quickActionSubtitle: {
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    lineHeight: 17,
    fontWeight: '500',
  },

  // Sections
  section: {
    marginTop: 18,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  sectionLink: {
    fontSize: 13,
    color: PASTEL_PALETTE.accentDeep,
    fontWeight: '700',
  },
  sectionBody: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },

  // Items
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PASTEL_PALETTE.border,
  },
  itemIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  itemContent: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: PASTEL_PALETTE.title,
  },
  itemSubtitle: {
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    marginTop: 2,
    fontWeight: '500',
  },
  itemValue: {
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
    marginRight: 4,
  },
  itemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  eyeIcon: {
    marginRight: 10,
  },

  // Security expand + modals
  securitySubList: {
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PASTEL_PALETTE.border,
  },
  securityMeasure: {
    position: 'absolute',
    opacity: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  securityCollapse: {
    overflow: 'hidden',
  },
  securitySubItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PASTEL_PALETTE.border,
  },
  securitySubIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  securityModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  securityModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  securityModalSheet: {
    backgroundColor: PASTEL_PALETTE.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 10,
    paddingHorizontal: 16,
    maxHeight: '90%',
  },
  securityModalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.border,
    marginBottom: 12,
  },
  securityModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  securityModalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  securityModalHint: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '500',
    lineHeight: 18,
    marginBottom: 16,
    paddingHorizontal: 2,
  },
  securityField: {
    marginBottom: 14,
  },
  securityLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  securityInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    minHeight: 48,
  },
  securityInputError: {
    borderColor: '#F87171',
  },
  securityInput: {
    flex: 1,
    fontSize: 15,
    color: PASTEL_PALETTE.title,
    fontWeight: '500',
    paddingVertical: 10,
  },
  securityError: {
    marginTop: 6,
    fontSize: 12,
    color: '#DC2626',
    fontWeight: '600',
  },
  securityForgotLink: {
    alignSelf: 'flex-end',
    marginBottom: 16,
    marginTop: 2,
  },
  securityForgotText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
  securityPrimaryBtn: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  securityPrimaryBtnText: {
    color: PASTEL_PALETTE.white,
    fontSize: 15,
    fontWeight: '800',
  },

  // Logout
  logoutContainer: {
    paddingHorizontal: 16,
    marginTop: 24,
    paddingBottom: 8,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1.5,
    borderColor: '#FECACA',
    borderRadius: 16,
    paddingVertical: 15,
    gap: 8,
  },
  logoutText: {
    color: '#DC2626',
    fontSize: 15,
    fontWeight: '800',
  },
  versionText: {
    textAlign: 'center',
    marginTop: 14,
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '500',
  },
});
