import { StyleSheet } from 'react-native';
import { FUND_PALETTE } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: FUND_PALETTE.bg,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    paddingBottom: 26,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginLeft: -4,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  balanceBlock: {
    marginTop: 22,
    alignItems: 'center',
  },
  themeTag: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 10,
  },
  themeTagText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  balanceLabel: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 13,
    fontWeight: '600',
  },
  balanceValue: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    marginTop: 6,
  },
  minDepositText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 8,
  },
  progressWrap: {
    width: '100%',
    marginTop: 18,
  },
  progressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  progressText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  sliderRow: {
    gap: 8,
    paddingRight: 8,
  },
  sliderChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: FUND_PALETTE.white,
    borderWidth: 1.5,
    borderColor: FUND_PALETTE.border,
  },
  sliderChipActive: {
    backgroundColor: FUND_PALETTE.primarySoft,
    borderColor: FUND_PALETTE.primary,
  },
  sliderChipDisabled: {
    opacity: 0.45,
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  sliderChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: FUND_PALETTE.subtitle,
  },
  sliderChipTextActive: {
    color: FUND_PALETTE.primaryDeep,
    fontWeight: '800',
  },
  sliderChipTextDisabled: {
    color: FUND_PALETTE.textMuted,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 8,
  },
  quickAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: FUND_PALETTE.primarySoft,
    borderWidth: 1,
    borderColor: FUND_PALETTE.borderSoft,
  },
  quickActionIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FUND_PALETTE.white,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: '700',
    color: FUND_PALETTE.primaryDeep,
  },
  quickActionDisabled: {
    opacity: 0.45,
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  quickActionIconDisabled: {
    backgroundColor: '#F9FAFB',
  },
  quickActionTextDisabled: {
    color: FUND_PALETTE.textMuted,
  },
  memberLimitHint: {
    marginBottom: 8,
    marginLeft: 4,
    fontSize: 12,
    fontWeight: '600',
    color: FUND_PALETTE.textMuted,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: FUND_PALETTE.primarySofter,
    borderRadius: 14,
    padding: 4,
    marginTop: 24,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: FUND_PALETTE.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: FUND_PALETTE.textMuted,
  },
  tabTextActive: {
    color: FUND_PALETTE.primaryDeep,
    fontWeight: '800',
  },
  card: {
    backgroundColor: FUND_PALETTE.white,
    borderRadius: 20,
    padding: 8,
    marginTop: 0,
    borderWidth: 1,
    borderColor: FUND_PALETTE.border,
  },
  membersTab: {
    marginTop: 16,
  },
  searchSection: {
    marginBottom: 4,
  },
  searchHint: {
    fontSize: 13,
    color: FUND_PALETTE.textMuted,
    marginBottom: 10,
    marginLeft: 4,
    fontWeight: '500',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FUND_PALETTE.white,
    paddingHorizontal: 14,
    borderRadius: 22,
    minHeight: 56,
    borderWidth: 1.5,
    borderColor: FUND_PALETTE.border,
    shadowColor: '#C084FC',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  searchIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: FUND_PALETTE.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    marginRight: 4,
    fontSize: 15,
    color: FUND_PALETTE.text,
    fontWeight: '500',
    paddingVertical: 0,
  },
  searchClearBtn: {
    padding: 4,
    marginRight: 6,
  },
  searchButton: {
    backgroundColor: FUND_PALETTE.primaryMid,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    shadowColor: FUND_PALETTE.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  searchButtonText: {
    color: FUND_PALETTE.white,
    fontWeight: '800',
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: FUND_PALETTE.title,
    marginTop: 16,
    marginBottom: 8,
    marginLeft: 4,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  memberInfo: {
    flex: 1,
    marginLeft: 12,
  },
  memberNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memberName: {
    fontSize: 15,
    fontWeight: '700',
    color: FUND_PALETTE.title,
    flexShrink: 1,
  },
  ownerBadge: {
    backgroundColor: FUND_PALETTE.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  ownerBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: FUND_PALETTE.primaryDeep,
  },
  invitedBadge: {
    backgroundColor: FUND_PALETTE.accentSoft,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  invitedBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#B45309',
  },
  memberContribLabel: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
    marginTop: 2,
  },
  memberContrib: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.primaryDeep,
  },
  txRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  txIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txInfo: {
    flex: 1,
    marginLeft: 12,
  },
  txTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  txName: {
    fontSize: 15,
    fontWeight: '700',
    color: FUND_PALETTE.title,
    flexShrink: 1,
  },
  txCatBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  txCatBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  leftBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  leftBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#DC2626',
  },
  txNote: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
    marginTop: 2,
  },
  txAmount: {
    fontSize: 15,
    fontWeight: '800',
  },
  emptyBlock: {
    alignItems: 'center',
    paddingVertical: 36,
    gap: 10,
  },
  emptyBlockText: {
    fontSize: 14,
    color: FUND_PALETTE.textMuted,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: FUND_PALETTE.title,
  },
  backLink: {
    marginTop: 12,
  },
  backLinkText: {
    color: FUND_PALETTE.primary,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  menuCard: {
    backgroundColor: FUND_PALETTE.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    paddingBottom: 34,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: FUND_PALETTE.title,
    marginBottom: 14,
  },
  menuItemDanger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  menuIconDanger: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemDangerText: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.danger,
  },
  menuItemSub: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
    marginTop: 2,
  },
  menuCancelBtn: {
    marginTop: 12,
    alignItems: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: FUND_PALETTE.primarySofter,
  },
  menuCancelText: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.primaryDeep,
  },
  modalCard: {
    backgroundColor: FUND_PALETTE.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    paddingBottom: 34,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#E5E7EB',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: FUND_PALETTE.title,
    marginBottom: 18,
  },
  modalCatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FUND_PALETTE.bgSoft,
    borderRadius: 16,
    padding: 12,
    gap: 12,
  },
  modalCatLabel: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
  },
  modalCatValue: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.title,
    marginTop: 2,
  },
  modalLock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  modalLockText: {
    fontSize: 11,
    fontWeight: '700',
    color: FUND_PALETTE.textMuted,
  },
  modalNoteLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: FUND_PALETTE.title,
    marginTop: 20,
    marginBottom: 10,
  },
  modalNoteInput: {
    backgroundColor: FUND_PALETTE.white,
    borderWidth: 1.5,
    borderColor: FUND_PALETTE.border,
    borderRadius: 16,
    padding: 14,
    fontSize: 15,
    color: FUND_PALETTE.title,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 22,
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.textMuted,
  },
  modalSaveBtn: {
    flex: 1.6,
    paddingVertical: 15,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: FUND_PALETTE.primary,
  },
  modalSaveText: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.white,
  },
  viewTxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  editMetaRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  editMetaItem: {
    flex: 1,
    backgroundColor: FUND_PALETTE.primarySofter,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: FUND_PALETTE.borderSoft,
  },
  editMetaValue: {
    fontSize: 14,
    fontWeight: '800',
    color: FUND_PALETTE.title,
    marginTop: 4,
  },
  viewNoteBox: {
    backgroundColor: FUND_PALETTE.primarySofter,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: FUND_PALETTE.borderSoft,
    minHeight: 56,
    marginBottom: 18,
  },
  viewNoteText: {
    fontSize: 15,
    color: FUND_PALETTE.title,
    lineHeight: 21,
  },
  viewCloseBtn: {
    width: '100%',
    paddingVertical: 15,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FUND_PALETTE.primary,
  },
  viewCloseBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: FUND_PALETTE.white,
  },
});
