package com.project.app.ai.finance;

public enum FinanceIntent {
    GUIDE,
    ASSETS_OVERVIEW,
    ASSETS_ALLOCATION,
    PERIOD_OVERVIEW,
    FINANCIAL_HEALTH,
    SPENDING_ANALYSIS,
    PERIOD_INCOME,
    PERIOD_EXPENSE,
    PERIOD_NET,
    SOURCE_WALLET,
    SOURCE_CASH,
    SOURCE_FUND,
    COMPARE_OVERVIEW,
    COMPARE_INCOME,
    COMPARE_EXPENSE,
    COMPARE_NET,
    COMPARE_WALLET,
    COMPARE_CASH,
    DELTA_SUMMARY,
    SPENDING_BY_CATEGORY,
    SPENDING_BY_CATEGORY_COMPARE,
    BUDGET_STATUS,
    FUND_BALANCE,
    NONE
}
