import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: PASTEL_PALETTE.bg },
  headerContent: { paddingHorizontal: 16, paddingBottom: 16 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.88)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.7)' },
  headerCopy: { flex: 1 },
  headerEyebrow: { fontSize: 11, fontWeight: '700', color: PASTEL_PALETTE.subtitle, letterSpacing: 0.5 },
  headerTitle: { marginTop: 1, fontSize: 20, fontWeight: '900', color: PASTEL_PALETTE.title, letterSpacing: -0.3 },
  loadingState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  loadingText: { fontSize: 13, fontWeight: '600', color: PASTEL_PALETTE.textMuted },
  scrollContent: { paddingHorizontal: 18, paddingTop: 24 },
  avatarSection: { alignItems: 'center', marginBottom: 26 },
  avatar: { width: 104, height: 104, borderRadius: 34, alignItems: 'center', justifyContent: 'center', backgroundColor: PASTEL_PALETTE.accentSoft, borderWidth: 3, borderColor: PASTEL_PALETTE.white, shadowColor: '#A855F7', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.16, shadowRadius: 16, elevation: 5 },
  avatarImage: { width: '100%', height: '100%', borderRadius: 31 },
  avatarInitials: { fontSize: 34, fontWeight: '900', color: PASTEL_PALETTE.accentDeep },
  cameraBadge: { position: 'absolute', right: -5, bottom: -5, width: 34, height: 34, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: PASTEL_PALETTE.accentDeep, borderWidth: 3, borderColor: PASTEL_PALETTE.bg },
  changePhotoText: { marginTop: 12, fontSize: 13, fontWeight: '800', color: PASTEL_PALETTE.accentDeep },
  errorBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, marginBottom: 18, padding: 13, borderRadius: 14, backgroundColor: '#FEF2F2' },
  errorText: { flex: 1, fontSize: 12, fontWeight: '600', lineHeight: 18, color: '#B91C1C' },
  sectionLabel: { marginBottom: 8, marginLeft: 2, fontSize: 12, fontWeight: '800', color: PASTEL_PALETTE.title },
  nameField: { height: 56, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 24, paddingHorizontal: 15, borderRadius: 16, borderWidth: 1.5, borderColor: PASTEL_PALETTE.accentSoft, backgroundColor: PASTEL_PALETTE.white },
  nameInput: { flex: 1, minWidth: 0, paddingVertical: 0, fontSize: 16, fontWeight: '700', color: PASTEL_PALETTE.title },
  counter: { fontSize: 11, fontWeight: '600', color: PASTEL_PALETTE.gray400 },
  infoList: { overflow: 'hidden', borderRadius: 20, backgroundColor: PASTEL_PALETTE.white },
  infoRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: PASTEL_PALETTE.border },
  infoRowLast: { borderBottomWidth: 0 },
  infoIcon: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginRight: 12, backgroundColor: PASTEL_PALETTE.accentSoft },
  infoCopy: { flex: 1, minWidth: 0 },
  infoLabel: { marginBottom: 3, fontSize: 11, fontWeight: '600', color: PASTEL_PALETTE.textMuted },
  infoValue: { fontSize: 14, fontWeight: '700', color: PASTEL_PALETTE.title },
  readOnlyHint: { marginTop: 10, paddingHorizontal: 4, fontSize: 11, fontWeight: '500', lineHeight: 17, color: PASTEL_PALETTE.textMuted },
  bottomBar: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 18, paddingTop: 12, backgroundColor: 'rgba(255,248,252,0.96)', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: PASTEL_PALETTE.border },
  saveButton: { height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 17, backgroundColor: PASTEL_PALETTE.accentDeep, shadowColor: PASTEL_PALETTE.accentDeep, shadowOffset: { width: 0, height: 7 }, shadowOpacity: 0.22, shadowRadius: 12, elevation: 4 },
  saveButtonDisabled: { opacity: 0.58 },
  saveButtonText: { fontSize: 15, fontWeight: '900', color: PASTEL_PALETTE.white },
})
