import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '../../../../shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
    paddingHorizontal: 16,
  },
  centerWrap: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
  },
  cardInner: {
    margin: 2,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderRadius: 22,
    padding: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  checkWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  headerSub: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  amountBlock: {
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 14,
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  amountLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  amountValue: {
    fontSize: 32,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    letterSpacing: -0.8,
  },
  amountCurrency: {
    fontSize: 20,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
  },
  flowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  flowParty: {
    width: '36%',
    alignItems: 'center',
    gap: 6,
  },
  flowLogo: {
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  bankLogoBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 4,
  },
  bankLogo: {
    width: 34,
    height: 22,
  },
  flowName: {
    fontSize: 13,
    fontWeight: '900',
  },
  brandSmart: {
    color: PASTEL_PALETTE.title,
  },
  brandSpend: {
    color: PASTEL_PALETTE.accent,
  },
  flowBankName: {
    fontSize: 12,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
  },
  flowArrowWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 4,
  },
  flowDash: {
    flex: 1,
    height: 1.5,
    backgroundColor: PASTEL_PALETTE.border,
  },
  flowArrowBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bankMeta: {
    textAlign: 'center',
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '600',
    marginBottom: 14,
  },
  metaBox: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
  },
  metaDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: PASTEL_PALETTE.border,
  },
  metaLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  metaValue: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    textAlign: 'right',
  },
  metaCode: {
    flexShrink: 1,
    maxWidth: '68%',
    fontSize: 12,
    fontWeight: '800',
    color: PASTEL_PALETTE.subtitle,
    textAlign: 'right',
    letterSpacing: 0.2,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: '68%',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  categoryChipText: {
    fontSize: 12,
    fontWeight: '700',
    flexShrink: 1,
  },
  feeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  feeBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  hintText: {
    marginTop: 12,
    fontSize: 12,
    lineHeight: 17,
    color: PASTEL_PALETTE.subtitle,
    fontWeight: '600',
    textAlign: 'center',
  },
  primaryButton: {
    marginTop: 16,
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: PASTEL_PALETTE.accent,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.white,
  },
});
