import { StyleSheet, Dimensions } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

const { width } = Dimensions.get('window')

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.white,
  },
  bgCircle: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.55,
  },
  circleTopLeft: {
    width: 350,
    height: 350,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    top: -100,
    left: -100,
  },
  circleBottomRight: {
    width: 450,
    height: 450,
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    bottom: -200,
    right: -150,
  },
  screenBody: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 16,
    zIndex: 1,
  },
  scrollView: {
    flex: 1,
  },
  slide: {
    width,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  textContainer: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
  },
  heroFrame: {
    width: Math.min(width * 0.92, 400),
    height: Math.min(width * 0.92, 400),
    borderRadius: Math.min(width * 0.92, 400) / 2,
    overflow: 'hidden',
    marginBottom: 22,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    position: 'relative',
  },
  heroLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  copyStack: {
    width: '100%',
    minHeight: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  stepTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
    lineHeight: 30,
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  stepSubtitle: {
    fontSize: 14,
    fontWeight: '500',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
    lineHeight: 21,
    maxWidth: 340,
    paddingHorizontal: 8,
  },
  title1: {
    fontSize: 28,
    fontWeight: '800',
    color: '#4B5563',
    textAlign: 'center',
    lineHeight: 40,
  },
  title2: {
    fontSize: 30,
    fontWeight: '900',
    color: '#111827',
    textAlign: 'center',
    lineHeight: 44,
  },
  highlight: {
    color: PASTEL_PALETTE.accentDeep,
  },
  badge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    marginBottom: 24,
  },
  badgeText: {
    color: PASTEL_PALETTE.accentDeep,
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 2,
  },
  title3: {
    fontSize: 34,
    fontWeight: '900',
    color: '#111827',
    textAlign: 'center',
    lineHeight: 46,
    marginBottom: 16,
  },
  subtitle3: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
  },
  ctaWrap: {
    width: '100%',
    paddingHorizontal: 32,
    paddingBottom: 28,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 50,
    left: 32,
    right: 32,
  },
  button: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    height: 56,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginRight: 8,
  },
  paginationContainer: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  progressBarBg: {
    flex: 1,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    marginHorizontal: 4,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 2,
  },
})
