import { StyleSheet, Platform } from "react-native";
import Colors from "../../../../shared/constants/Colors";
import { PASTEL_PALETTE } from "../../../../shared/constants/PastelPalette";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  header: {
    paddingBottom: 18,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
    marginLeft: -8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 22,
    fontWeight: "900",
    color: PASTEL_PALETTE.title,
    letterSpacing: 0.2,
  },
  content: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: PASTEL_PALETTE.title,
    marginBottom: 16,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  rowLabelContainer: {
    flex: 1,
    marginRight: 16,
  },
  rowTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: PASTEL_PALETTE.title,
    marginBottom: 4,
  },
  rowSubtitle: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    lineHeight: 18,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginTop: 8,
  },
  currencySymbol: {
    fontSize: 16,
    fontWeight: "600",
    color: PASTEL_PALETTE.subtitle,
    marginRight: 8,
  },
  input: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: PASTEL_PALETTE.title,
    padding: 0,
    margin: 0,
  },
  divider: {
    height: 1,
    backgroundColor: PASTEL_PALETTE.border,
    marginVertical: 16,
  },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: "transparent",
  },
  saveButton: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: "center",
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  saveButtonDisabled: {
    backgroundColor: Colors.border,
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: PASTEL_PALETTE.white,
  },
  saveButtonTextDisabled: {
    color: PASTEL_PALETTE.textMuted,
  },
  infoSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  infoText: {
    fontSize: 13,
    color: PASTEL_PALETTE.subtitle,
    fontWeight: "500",
    marginLeft: 12,
    flex: 1,
    lineHeight: 20,
  },
  statLabel: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 15,
    fontWeight: "600",
    color: PASTEL_PALETTE.title,
  },
  progressTrack: {
    height: 6,
    backgroundColor: PASTEL_PALETTE.border,
    borderRadius: 3,
    marginTop: 16,
    marginBottom: 8,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 3,
  },
});
