import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.75)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  headerRightSpacer: {
    width: 40,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  card: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 22,
    marginBottom: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(243, 232, 255, 0.95)',
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 3,
  },
  successStrip: {
    height: 4,
    width: '100%',
  },
  summaryBlock: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 8,
  },
  summaryTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  summaryTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 4,
  },
  summarySubtitle: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
    lineHeight: 18,
  },
  summaryAmount: {
    marginTop: 14,
    fontSize: 32,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    letterSpacing: 0.3,
  },
  recipientBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  recipientBannerText: {
    flex: 1,
    minWidth: 0,
  },
  recipientBannerLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
    marginBottom: 2,
  },
  recipientBannerName: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  detailsBlock: {
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    paddingVertical: 12,
  },
  rowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F3E8FF',
  },
  rowLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  rowValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textDark,
  },
  rowValueMuted: {
    color: PASTEL_PALETTE.gray400,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  statusText: {
    color: '#15803D',
    fontSize: 12,
    fontWeight: '800',
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    maxWidth: '70%',
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '700',
  },
  closeBtn: {
    marginTop: 6,
    height: 54,
    borderRadius: 16,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 3,
  },
  closeBtnText: {
    color: PASTEL_PALETTE.white,
    fontSize: 16,
    fontWeight: '800',
  },
})
