import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  headerRightSpacer: {
    width: 40,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  receiptCard: {
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: 'rgba(243, 232, 255, 0.9)',
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 4,
    marginBottom: 16,
  },
  receiptBg: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.55,
  },
  receiptInner: {
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 20,
  },
  successBadge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#22C55E',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 4,
  },
  successTitle: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  successAmount: {
    textAlign: 'center',
    fontSize: 30,
    fontWeight: '900',
    color: PASTEL_PALETTE.textDark,
    letterSpacing: 0.2,
    marginBottom: 8,
  },
  successHint: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    lineHeight: 19,
    marginBottom: 22,
    paddingHorizontal: 8,
  },
  partiesBlock: {
    marginBottom: 18,
    paddingHorizontal: 4,
  },
  partyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  partyAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    overflow: 'hidden',
  },
  partyText: {
    flex: 1,
    minWidth: 0,
  },
  partyName: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 2,
  },
  partySub: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  partyConnector: {
    alignItems: 'center',
    paddingVertical: 4,
    paddingLeft: 20,
  },
  partyDotLine: {
    width: 2,
    height: 10,
    borderRadius: 1,
    backgroundColor: '#D1D5DB',
  },
  partyChevron: {
    marginVertical: 2,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#E5E7EB',
    marginBottom: 6,
  },
  detailsBlock: {
    paddingTop: 2,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 11,
  },
  rowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F3E8FF',
  },
  rowLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  rowValueWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    minWidth: 0,
  },
  rowValue: {
    flexShrink: 1,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textDark,
  },
  rowValueMuted: {
    color: PASTEL_PALETTE.gray400,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  tagBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  tagBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    maxWidth: '72%',
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '700',
  },
  categoryReminderCard: {
    minHeight: 154,
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F3D9EA',
    backgroundColor: '#FFF5FA',
  },
  categoryReminderBackground: {
    borderRadius: 20,
  },
  categoryReminderContent: {
    width: '59%',
    zIndex: 1,
    marginLeft: 18,
    paddingVertical: 14,
  },
  categoryReminderLabel: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 7,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  categoryReminderLabelText: {
    fontSize: 10,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  categoryReminderTitle: {
    marginBottom: 5,
    fontSize: 14,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  categoryReminderText: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    color: PASTEL_PALETTE.textMuted,
  },
  closeBtn: {
    height: 54,
    borderRadius: 16,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 3,
  },
  closeBtnText: {
    color: PASTEL_PALETTE.white,
    fontSize: 16,
    fontWeight: '800',
  },
  noteOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 22,
    backgroundColor: 'rgba(15,23,42,0.38)',
  },
  noteBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  noteCard: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  noteTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 10,
  },
  noteInput: {
    minHeight: 90,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
    fontSize: 14,
    color: PASTEL_PALETTE.textDark,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  noteActions: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  noteCancelBtn: {
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.white,
  },
  noteCancelText: {
    color: PASTEL_PALETTE.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  noteSaveBtn: {
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.accentDeep,
  },
  noteSaveBtnDisabled: {
    opacity: 0.6,
  },
  noteSaveText: {
    color: PASTEL_PALETTE.white,
    fontSize: 13,
    fontWeight: '800',
  },
})
