import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const moneyFlowStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.75)',
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
    marginTop: 4,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingHorizontal: 14,
    minHeight: 54,
  },
  inputBoxError: {
    borderColor: '#EF4444',
  },
  amountInput: {
    flex: 1,
    fontSize: 22,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    paddingVertical: 12,
  },
  currency: {
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  noteInput: {
    flex: 1,
    fontSize: 14,
    color: PASTEL_PALETTE.textDark,
    paddingVertical: 12,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
    marginBottom: 16,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  chipActive: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderColor: PASTEL_PALETTE.accentDeep,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
  },
  chipTextActive: {
    color: PASTEL_PALETTE.white,
  },
  selector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    paddingHorizontal: 14,
    minHeight: 54,
    marginBottom: 4,
  },
  selectorText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: PASTEL_PALETTE.title,
  },
  bankCard: {
    minWidth: 220,
    maxWidth: 260,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginRight: 10,
  },
  bankCardActive: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  bankLogo: {
    flexShrink: 0,
  },
  bankInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  bankName: {
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  bankAccount: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  emptyBankBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.white,
    padding: 16,
    marginBottom: 12,
  },
  emptyBankText: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 10,
    lineHeight: 19,
  },
  linkBankBtn: {
    alignSelf: 'flex-start',
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  linkBankText: {
    color: PASTEL_PALETTE.subtitle,
    fontWeight: '700',
    fontSize: 13,
  },
  primaryBtn: {
    marginTop: 24,
    height: 54,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnDisabled: {
    opacity: 0.65,
  },
  primaryBtnText: {
    color: PASTEL_PALETTE.white,
    fontSize: 16,
    fontWeight: '800',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 4,
  },
  sepayContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },
  sepayLoadingState: {
    flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32, gap: 12,
  },
  sepayLoadingText: {
    textAlign: 'center', fontSize: 13, lineHeight: 19, color: PASTEL_PALETTE.textMuted,
  },
  sepayErrorTitle: { fontSize: 17, fontWeight: '900', color: PASTEL_PALETTE.title },
  sepayRetryButton: {
    marginTop: 6, paddingHorizontal: 20, paddingVertical: 11, borderRadius: 13,
    backgroundColor: PASTEL_PALETTE.accentDeep,
  },
  sepayRetryText: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },
  sepayCard: {
    padding: 18, borderRadius: 24, backgroundColor: PASTEL_PALETTE.white, borderWidth: 1,
    borderColor: PASTEL_PALETTE.border, shadowColor: '#7357A5', shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1, shadowRadius: 20, elevation: 4,
  },
  sepayBrandRow: { flexDirection: 'row', alignItems: 'center' },
  sepayBrandIcon: {
    width: 42, height: 42, marginRight: 10, borderRadius: 13, alignItems: 'center',
    justifyContent: 'center', backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  sepayBrandCopy: { flex: 1 },
  sepayBrandTitle: { fontSize: 14, fontWeight: '900', color: PASTEL_PALETTE.title },
  sepayBrandSubtitle: { marginTop: 2, fontSize: 11, color: PASTEL_PALETTE.textMuted },
  sepayLiveBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 5,
    borderRadius: 999, backgroundColor: '#EAF6EF',
  },
  sepayLiveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#2D8A61' },
  sepayLiveText: { fontSize: 9, fontWeight: '900', color: '#2D8A61' },
  sepayQrFrame: {
    alignSelf: 'center', width: 270, height: 270, marginTop: 18, padding: 8,
    borderRadius: 20, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8E0EF',
  },
  sepayQrImage: { width: '100%', height: '100%' },
  sepayTransferBox: { marginTop: 17, padding: 14, borderRadius: 15, backgroundColor: '#F6F1FB' },
  sepayTransferLabel: { textAlign: 'center', fontSize: 11, fontWeight: '700', color: PASTEL_PALETTE.textMuted },
  sepayTransferContent: {
    marginTop: 5, textAlign: 'center', fontSize: 17, fontWeight: '900', letterSpacing: 0.5,
    color: PASTEL_PALETTE.accentDeep,
  },
  sepayNotice: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 14 },
  sepayNoticeText: { flex: 1, fontSize: 11, lineHeight: 16, color: PASTEL_PALETTE.subtitle },
  balanceCard: {
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    marginBottom: 22,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 4,
  },
  withdrawBalanceCard: {
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    marginBottom: 24,
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  withdrawBalanceIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  withdrawBalanceMetaRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PASTEL_PALETTE.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  withdrawStepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 5,
  },
  withdrawStepIndex: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  withdrawStepIndexText: {
    fontSize: 11,
    fontWeight: '900',
    color: PASTEL_PALETTE.accentDeep,
  },
  withdrawStepTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  withdrawFieldHint: {
    marginLeft: 32,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
    color: PASTEL_PALETTE.textMuted,
  },
  withdrawOptional: {
    marginLeft: 'auto',
    fontSize: 10,
    fontWeight: '700',
    color: PASTEL_PALETTE.gray400,
  },
  withdrawButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  balanceDecor: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.28)',
    top: -36,
    right: -28,
  },
  balanceDecorSmall: {
    position: 'absolute',
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.2)',
    bottom: -18,
    left: -12,
  },
  balanceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  balanceIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
    marginBottom: 4,
  },
  balanceValue: {
    fontSize: 28,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    letterSpacing: 0.2,
  },
  balanceMetaRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.55)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  balanceMetaLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  balanceMetaValue: {
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  balanceMetaWarn: {
    color: '#DC2626',
  },
  limitSection: {
    marginTop: 0,
  },
  limitDivider: {
    height: 1,
    backgroundColor: 'rgba(124,58,237,0.12)',
    marginHorizontal: -2,
    marginTop: 14,
    marginBottom: 12,
  },
  limitToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 4,
  },
  limitToggleTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  limitToggleTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  limitToggleSummary: {
    fontSize: 11,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '600',
    marginTop: 3,
  },
  limitDetails: {
    paddingTop: 8,
  },
  limitMeasureWrap: {
    position: 'absolute',
    opacity: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  limitRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  limitRowSpacing: {
    marginTop: 12,
  },
  limitLabel: {
    color: PASTEL_PALETTE.textMuted,
    fontSize: 13,
    flex: 1,
    paddingRight: 8,
  },
  limitValue: {
    color: PASTEL_PALETTE.title,
    fontSize: 14,
    fontWeight: '600',
  },
  limitPlaceholder: {
    color: PASTEL_PALETTE.lavender,
    fontSize: 13,
    fontStyle: 'italic',
  },
  limitStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  limitStatBlock: {
    flex: 1,
  },
  limitStatBlockEnd: {
    flex: 1,
    alignItems: 'flex-end',
  },
  limitStatLabel: {
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  limitStatValue: {
    fontSize: 14,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  limitStatHint: {
    textAlign: 'right',
    marginTop: 6,
  },
  limitProgressTrack: {
    height: 6,
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    borderRadius: 3,
    marginTop: 10,
    overflow: 'hidden',
  },
  limitProgressFill: {
    height: '100%',
    borderRadius: 3,
  },
})
