package com.project.app.notification.enums;

public enum NotificationType {
    GENERAL,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    FUND_INVITE,
    FUND_INVITE_ACCEPTED,
    INVOICE_REMINDER,
    BUDGET_WARNING,
    BUDGET_EXCEEDED,
    NOTEBOOK_REMINDER,
    SPLIT_BILL_REQUEST,
    SPLIT_BILL_PAID,
    SPLIT_BILL_REMINDER,
    TRANSFER_RECEIVED,
    WITHDRAW_SUCCESS,
    TOP_UP_SUCCESS,
    FUND_DEPOSIT,
    FUND_WITHDRAW,
    FUND_GOAL_REACHED,
    FUND_CLOSED,
    SPLIT_BILL_COMPLETED,
    SPLIT_BILL_CANCELLED,
    INVOICE_PAYMENT_SUCCESS,
    INVOICE_DUE_TODAY,
    INVOICE_OVERDUE
}
