package com.project.app.notification.enums;

public enum NotificationType {
    GENERAL,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    FUND_INVITE,
    FUND_INVITE_ACCEPTED,
    INVOICE_REMINDER,
    BUDGET_WARNING,
    BUDGET_EXCEEDED,
    NOTEBOOK_REMINDER,
    SPLIT_BILL_REQUEST,
    SPLIT_BILL_PAID,
    SPLIT_BILL_REMINDER
}
