import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginTop: 13,
    minHeight: 82,
    padding: 13,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#FFFDFC',
    borderWidth: 1,
    borderColor: '#EEE3ED',
  },
  iconWrap: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9E8F3',
  },
  copy: { flex: 1, minWidth: 0, marginLeft: 12 },
  eyebrow: { fontSize: 9, fontWeight: '900', letterSpacing: 0.8, color: '#A27A9B' },
  title: { marginTop: 1, fontSize: 16, fontWeight: '900', color: '#322735' },
  subtitle: { marginTop: 3, fontSize: 10, lineHeight: 14, color: '#807181' },
  openButton: { marginLeft: 8, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 7 },
  openButtonText: { fontSize: 11, fontWeight: '900', color: '#6D4AAF' },
  overlay: {
    flex: 1,
    paddingHorizontal: 18,
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 248, 252, 0.94)',
  },
  backdrop: { ...StyleSheet.absoluteFillObject },
  modalCard: {
    width: '100%',
    maxWidth: 390,
    alignSelf: 'center',
    padding: 18,
    borderRadius: 28,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EADDE9',
    shadowColor: '#5B2E61',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
    maxHeight: '95%',
  },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerSpacer: { width: 40, height: 40 },
  modalHeading: { flex: 1, alignItems: 'center', paddingHorizontal: 6 },
  modalEyebrow: { fontSize: 10, fontWeight: '900', letterSpacing: 0.8, color: '#A17B9D' },
  modalTitle: { marginTop: 3, fontSize: 21, fontWeight: '900', letterSpacing: -0.4, color: '#302433' },
  closeButton: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7F1F6' },
  tabBar: {
    height: 48,
    marginTop: 16,
    padding: 4,
    flexDirection: 'row',
    borderRadius: 16,
    backgroundColor: '#F6F0F5',
  },
  tabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 12,
  },
  tabItemActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#6D4AAF',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  tabText: { fontSize: 11, fontWeight: '800', color: '#8D818F' },
  tabTextActive: { color: '#6D4AAF' },
  tabDemoBadge: { paddingHorizontal: 5, paddingVertical: 2, borderRadius: 5, backgroundColor: '#F7DDEA' },
  tabDemoText: { fontSize: 7, fontWeight: '900', letterSpacing: 0.4, color: '#A32768' },
  loadingState: { minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: 12 },
  choiceWrap: { paddingTop: 18 },
  choiceLead: { paddingHorizontal: 8, marginBottom: 14, fontSize: 12, lineHeight: 18, textAlign: 'center', color: '#817383' },
  choiceCard: {
    minHeight: 82,
    marginBottom: 11,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#FFFCFE',
    borderWidth: 1,
    borderColor: '#EEE3ED',
  },
  internalChoiceIcon: { width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0EAFE' },
  bankChoiceIcon: { width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FCE8F2' },
  choiceCopy: { flex: 1, minWidth: 0, marginHorizontal: 12 },
  choiceTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  choiceTitle: { fontSize: 15, fontWeight: '900', color: '#382D3B' },
  choiceText: { marginTop: 4, fontSize: 11, lineHeight: 16, color: '#817383' },
  demoMiniBadge: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, backgroundColor: '#F9D9EA' },
  demoMiniText: { fontSize: 8, fontWeight: '900', letterSpacing: 0.7, color: '#A32768' },
  choiceHint: { marginTop: 3, padding: 12, flexDirection: 'row', alignItems: 'flex-start', gap: 9, borderRadius: 15, backgroundColor: '#F6F1FC' },
  choiceHintText: { flex: 1, fontSize: 10, lineHeight: 15, color: '#6E6171' },
  transferContent: { width: '100%' },
  demoBanner: { marginTop: 16, alignSelf: 'center', paddingHorizontal: 11, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 99, backgroundColor: '#FBE5F0' },
  demoBannerText: { fontSize: 9, fontWeight: '900', letterSpacing: 0.6, color: '#A32768' },
  bankQrFrame: {
    width: 258,
    height: 258,
    marginTop: 12,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 26,
    backgroundColor: '#FFF1F7',
  },
  bankQrMark: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D93E8C',
    borderWidth: 3,
    borderColor: '#FFF',
  },
  demoNotice: { marginTop: 14, padding: 12, flexDirection: 'row', alignItems: 'flex-start', gap: 9, borderRadius: 15, backgroundColor: '#FFF0F5', borderWidth: 1, borderColor: '#F5CFDF' },
  demoNoticeText: { flex: 1, fontSize: 10, lineHeight: 16, color: '#8B3A60' },
  qrFrame: {
    width: 258,
    height: 258,
    marginTop: 18,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 26,
    backgroundColor: '#F6EEF5',
  },
  qrInner: { padding: 12, borderRadius: 18, backgroundColor: '#FFF' },
  qrMark: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EC4899',
    borderWidth: 3,
    borderColor: '#FFF',
  },
  ownerName: { marginTop: 15, fontSize: 17, fontWeight: '900', textAlign: 'center', color: '#302433' },
  accountLabel: { marginTop: 7, fontSize: 10, fontWeight: '700', textAlign: 'center', color: '#8A7B8C' },
  accountNumber: { marginTop: 2, fontSize: 19, fontWeight: '900', letterSpacing: 1.1, textAlign: 'center', color: '#6D4AAF', fontVariant: ['tabular-nums'] },
  hint: { marginTop: 11, paddingHorizontal: 14, fontSize: 11, lineHeight: 17, textAlign: 'center', color: '#817383' },
  shareButton: {
    height: 50,
    marginTop: 16,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#EC4899',
  },
  shareButtonText: { fontSize: 13, fontWeight: '900', color: '#FFF' },
  unavailableState: { minHeight: 300, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 30 },
  unavailableTitle: { marginTop: 13, fontSize: 16, fontWeight: '900', color: '#382D3B' },
  unavailableText: { marginTop: 6, fontSize: 12, lineHeight: 18, textAlign: 'center', color: '#817383' },
})
