import { StyleSheet } from "react-native";
import Colors from "../../../shared/constants/Colors";

export const PALETTE = {
  bg: '#FFF8FC',
  headerStart: '#FFD6EC',
  headerMid: '#E9D5FF',
  headerEnd: '#BFDBFE',
  accent: '#F472B6',
  accentDeep: '#EC4899',
  accentSoft: '#FCE7F3',
  lavender: '#A78BFA',
  lavenderSoft: '#EDE9FE',
  title: '#5B21B6',
  subtitle: '#7C3AED',
  textMuted: '#6B7280',
  white: '#FFFFFF',
  border: '#F3E8FF',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.bg,
  },
  headerWrap: {
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    marginBottom: 4,
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 18,
  },
  headerDecorCircleLarge: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    top: -24,
    right: -20,
  },
  headerDecorCircleSmall: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    bottom: 18,
    left: 18,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 10,
  },
  leftSection: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginLeft: -8,
  },
  titleContainer: {
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#7C3AED',
    fontWeight: "600",
    marginTop: 4,
    opacity: 0.85,
  },
  addButton: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 18,
    backgroundColor: PALETTE.accent,
    shadowColor: PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  addButtonText: {
    color: PALETTE.white,
    fontSize: 12,
    fontWeight: '800',
  },
  addButtonDisabled: {
    opacity: 0.45,
  },
  headerHintBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.85)',
  },
  headerHintContent: {
    gap: 5,
  },
  headerHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  headerHintText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    color: '#6D28D9',
    fontWeight: '600',
  },
  topActionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    gap: 12,
    backgroundColor: PALETTE.bg,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PALETTE.white,
    borderRadius: 22,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1.5,
    borderColor: PALETTE.border,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    color: Colors.text,
  },
  scrollContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  groupSwipeContainer: {
    marginBottom: 16,
  },
  groupCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  swipeDeleteActionWrap: {
    width: 96,
    marginLeft: 10,
  },
  swipeDeleteButton: {
    flex: 1,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#DC2626',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 4,
  },
  swipeDeleteGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 14,
    minHeight: '100%',
  },
  swipeDeleteIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  swipeDeleteText: {
    color: Colors.white,
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  swipeDeleteSubtext: {
    color: 'rgba(255, 255, 255, 0.88)',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  groupHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    paddingTop: 2,
  },
  groupHeaderActions: {
    alignItems: 'flex-end',
    maxWidth: '46%',
  },
  groupAddCategoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
  },
  groupAddCategoryBtnDisabled: {
    backgroundColor: 'rgba(0, 0, 0, 0.06)',
    borderColor: '#D1D5DB',
    opacity: 0.75,
  },
  groupAddCategoryText: {
    fontSize: 12,
    fontWeight: '700',
  },
  groupLimitHint: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '500',
    color: '#6B7280',
    textAlign: 'right',
    lineHeight: 14,
  },
  groupTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  emptyGroupContainer: {
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  emptyGroupText: {
    fontSize: 14,
    color: PALETTE.subtitle,
    fontStyle: 'italic',
    fontWeight: '500',
    opacity: 0.85,
  },
  emptyStateContainer: {
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 40,
  },
  setupHero: {
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 20,
  },
  setupStepsCard: {
    backgroundColor: PALETTE.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: PALETTE.border,
    shadowColor: PALETTE.lavender,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  setupStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 16,
    gap: 12,
  },
  setupStepRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: PALETTE.border,
  },
  setupStepBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: PALETTE.accentDeep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setupStepBadgeText: {
    color: PALETTE.white,
    fontSize: 13,
    fontWeight: '800',
  },
  setupStepContent: {
    flex: 1,
  },
  setupStepTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  setupStepTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: PALETTE.title,
  },
  setupStepDescription: {
    fontSize: 13,
    color: PALETTE.subtitle,
    lineHeight: 19,
    fontWeight: '500',
    opacity: 0.9,
  },
  setupCtaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: PALETTE.accentDeep,
    paddingVertical: 14,
    borderRadius: 14,
    marginHorizontal: 8,
    shadowColor: PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 3,
  },
  setupCtaText: {
    color: PALETTE.white,
    fontSize: 15,
    fontWeight: '700',
  },
  emptyStateTitle: {
    marginTop: 16,
    color: PALETTE.title,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyStateHint: {
    marginTop: 8,
    color: PALETTE.subtitle,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 21,
    paddingHorizontal: 8,
    fontWeight: '500',
    opacity: 0.88,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 16,
    paddingBottom: 8,
    gap: 16,
  },
  gridItem: {
    width: '21%', // Fits 4 items per row with gap
    alignItems: 'center',
    marginBottom: 16,
  },
  iconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemLabel: {
    fontSize: 12,
    color: Colors.text,
    textAlign: 'center',
    lineHeight: 16,
  },
  deleteBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: Colors.white,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
