import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.75)',
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  exportBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.75)',
  },
  tabs: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    padding: 4,
    borderRadius: 16,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  tab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 12,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: PASTEL_PALETTE.white,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  tabTextActive: {
    color: PASTEL_PALETTE.title,
  },
  body: {
    flex: 1,
  },
  overviewPad: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 40,
  },
  nestedPad: {
    paddingHorizontal: 16,
    paddingTop: 4,
    marginBottom: 12,
  },
  comparePad: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  loadingWrap: {
    paddingVertical: 64,
    alignItems: 'center',
  },
  periodChips: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  periodChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  periodChipActive: {
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderColor: PASTEL_PALETTE.accentDeep,
  },
  periodChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  periodChipTextActive: {
    color: PASTEL_PALETTE.title,
  },
  dateSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    gap: 12,
  },
  dateNavBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  dateTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  dateText: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginLeft: 8,
  },
  compareToText: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    textAlign: 'center',
  },
  card: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 4,
  },
  noteText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#7C3AED',
    marginBottom: 8,
  },
  assetHeroOuter: {
    borderRadius: 22,
    marginBottom: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 5,
  },
  assetHeroGradient: {
    padding: 16,
    borderRadius: 22,
    overflow: 'hidden',
  },
  assetHeroBlobA: {
    position: 'absolute',
    top: -28,
    right: -20,
    width: 96,
    height: 96,
    borderRadius: 999,
    backgroundColor: 'rgba(236, 72, 153, 0.12)',
  },
  assetHeroBlobB: {
    position: 'absolute',
    bottom: -34,
    left: -18,
    width: 110,
    height: 110,
    borderRadius: 999,
    backgroundColor: 'rgba(167, 139, 250, 0.14)',
  },
  assetHeroHeader: {
    gap: 8,
    marginBottom: 6,
  },
  assetTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  assetTitleIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetHeroTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  assetNotePill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderWidth: 1,
    borderColor: '#E9D5FF',
  },
  assetNoteText: {
    fontSize: 11,
    fontWeight: '800',
    color: PASTEL_PALETTE.subtitle,
  },
  assetHeroAmount: {
    fontSize: 30,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
    letterSpacing: -0.5,
    marginBottom: 14,
  },
  assetVisualRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  assetDonutShell: {
    width: 168,
    height: 168,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetDonutGlow: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 999,
    backgroundColor: 'rgba(167, 139, 250, 0.22)',
  },
  assetDonutCanvas: {
    width: 156,
    height: 156,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetCenterWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  assetCenterPct: {
    fontSize: 13,
    fontWeight: '900',
    color: PASTEL_PALETTE.accentDeep,
  },
  assetCenterPctDivider: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  waveDividerWrap: {
    width: 28,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetLegendStack: {
    flex: 1,
    gap: 10,
  },
  assetLegendCard: {
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderWidth: 1,
    gap: 4,
  },
  assetLegendHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  assetNotebookIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetLegendName: {
    flex: 1,
    fontSize: 11,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    minWidth: 0,
  },
  assetLegendPct: {
    marginLeft: 30,
    fontSize: 12,
    fontWeight: '900',
  },
  assetLegendAmount: {
    marginLeft: 30,
    fontSize: 13,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  cardHint: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 12,
  },
  columnChartWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    gap: 10,
  },
  columnChartBars: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  columnChartYAxis: {
    fontSize: 10,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  columnChartXLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  columnChartSide: {
    flex: 1,
    gap: 10,
    justifyContent: 'center',
  },
  columnChartSideRow: {
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  columnChartSideTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  columnChartDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  columnChartSideLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  columnChartSideAmount: {
    fontSize: 13,
    fontWeight: '900',
    color: PASTEL_PALETTE.title,
  },
  chartHint: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    color: PASTEL_PALETTE.textMuted,
  },
  breakdownList: {
    gap: 10,
  },
  breakdownRow: {
    gap: 6,
  },
  breakdownTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  breakdownLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  breakdownAmount: {
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  breakdownTrack: {
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  breakdownFill: {
    height: 8,
    borderRadius: 999,
  },
  breakdownPercent: {
    alignSelf: 'flex-end',
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.subtitle,
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  summaryCell: {
    flex: 1,
    borderRadius: 14,
    padding: 10,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  summaryDelta: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '800',
  },
  metricBlock: {
    marginBottom: 12,
  },
  metricTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  barRow: {
    marginBottom: 8,
  },
  barMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  barLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  barValue: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  barTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.gray100,
    overflow: 'hidden',
  },
  barFill: {
    height: 8,
    borderRadius: 999,
  },
  insight: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
    lineHeight: 20,
    marginTop: 4,
  },
  analyzeBtn: {
    marginTop: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  analyzeBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '800',
  },
  compareSegment: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 10,
  },
  compareSegmentItem: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
  },
  compareSegmentItemActive: {
    backgroundColor: PASTEL_PALETTE.white,
  },
  compareSegmentText: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  compareSegmentTextActive: {
    color: PASTEL_PALETTE.title,
  },
  comparePresetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
  },
  comparePresetText: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
  comparePeriodBox: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: 16,
    borderWidth: 1,
    padding: 10,
    gap: 4,
  },
  comparePeriodHalf: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 96,
  },
  comparePeriodBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    marginBottom: 6,
  },
  comparePeriodBadgeB: {
    backgroundColor: '#EDE9FE',
  },
  comparePeriodBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
    textTransform: 'uppercase',
  },
  comparePeriodBadgeTextB: {
    color: PASTEL_PALETTE.lavender,
  },
  comparePeriodLabel: {
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 18,
    marginVertical: 4,
  },
  comparePeriodNav: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  compareNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.white,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  compareNavBtnDisabled: {
    opacity: 0.35,
  },
  comparePeriodVsWrap: {
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  comparePeriodVs: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  analysisRow: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    padding: 10,
    marginBottom: 10,
  },
  analysisTotalRow: {
    borderRadius: 14,
    borderWidth: 1.5,
    padding: 12,
    marginBottom: 12,
  },
  analysisTotalLabel: {
    fontSize: 13,
    fontWeight: '900',
    color: PASTEL_PALETTE.accentDeep,
    marginBottom: 10,
  },
  analysisTotalAmounts: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  analysisAmountCell: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: PASTEL_PALETTE.white,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  analysisAmountPeriod: {
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  analysisAmountValue: {
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  analysisAmountVs: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  analysisTotalSummary: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    lineHeight: 18,
  },
  analysisSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  analysisLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 4,
  },
  analysisText: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    lineHeight: 18,
  },
  rankColumns: {
    flexDirection: 'row',
    gap: 10,
  },
  rankCol: {
    flex: 1,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 12,
    padding: 10,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  rankTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  rankRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginBottom: 7,
  },
  rankIdx: {
    fontSize: 12,
    fontWeight: '800',
    color: PASTEL_PALETTE.textMuted,
    width: 18,
  },
  rankName: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  rankAmount: {
    fontSize: 11,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginTop: 1,
  },
  rankEmpty: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
})
