import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerContent: { paddingHorizontal: 18, paddingBottom: 22 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.76)',
  },
  headerCopy: { flex: 1, minWidth: 0 },
  headerEyebrow: { fontSize: 8, fontWeight: '900', letterSpacing: 1, color: '#8A6A85' },
  headerTitle: { marginTop: 2, fontSize: 22, fontWeight: '900', letterSpacing: -0.6, color: PASTEL_PALETTE.title },
  headerSubtitle: { marginTop: 2, fontSize: 9, fontWeight: '600', color: PASTEL_PALETTE.subtitle },
  tabsScroller: { flexGrow: 0, marginTop: 10 },
  tabs: { paddingHorizontal: 14, gap: 8 },
  tab: {
    height: 38,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
  },
  tabActive: {
    shadowColor: '#6D4AAF',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  tabText: { fontSize: 10, fontWeight: '800' },
  body: { flex: 1 },
  bodyContent: { padding: 16, paddingTop: 12, paddingBottom: 46 },
  reportBody: { flex: 1, paddingTop: 10 },
  reportInset: { flex: 1, marginHorizontal: 16 },
  contextBanner: {
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
  },
  contextText: { flex: 1, fontSize: 10, lineHeight: 15, fontWeight: '600' },
  periodWrap: { marginBottom: 12 },
  periodSegments: {
    padding: 4,
    flexDirection: 'row',
    borderRadius: 14,
    backgroundColor: '#EEE7EF',
  },
  periodSegment: { flex: 1, minHeight: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 10 },
  periodSegmentActive: { backgroundColor: '#FFF', elevation: 2 },
  periodSegmentText: { fontSize: 10, fontWeight: '700', color: '#8D808E' },
  periodSegmentTextActive: { fontWeight: '900', color: '#6D4AAF' },
  dateNav: { marginTop: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 },
  dateButton: { width: 31, height: 31, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F1E9FA' },
  dateLabel: { minWidth: 110, textAlign: 'center', fontSize: 11, fontWeight: '900', color: '#4A3B4D' },
  disabled: { opacity: 0.35 },
  loading: { minHeight: 280, alignItems: 'center', justifyContent: 'center' },
  errorCard: { minHeight: 180, padding: 24, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  errorText: { marginTop: 9, textAlign: 'center', fontSize: 12, fontWeight: '700' },
  hero: {
    padding: 17,
    borderRadius: 24,
    borderWidth: 1,
    shadowColor: '#72527D',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.1,
    shadowRadius: 17,
    elevation: 4,
  },
  heroEyebrow: { fontSize: 9, fontWeight: '900', letterSpacing: 0.9 },
  heroValue: { marginTop: 4, fontSize: 28, fontWeight: '900', letterSpacing: -0.8, fontVariant: ['tabular-nums'] },
  heroHint: { marginTop: 3, fontSize: 10, fontWeight: '600' },
  balanceRow: { marginTop: 15, paddingTop: 13, flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#EEE5EE' },
  balanceItem: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  balanceLabel: { fontSize: 9, fontWeight: '700', color: '#928493' },
  balanceValue: { marginTop: 1, fontSize: 12, fontWeight: '900', color: '#433645', fontVariant: ['tabular-nums'] },
  divider: { width: 1, marginHorizontal: 12 },
  metrics: { marginTop: 10, flexDirection: 'row', gap: 10 },
  metricCard: { flex: 1, padding: 13, borderRadius: 18, borderWidth: 1 },
  metricIcon: { width: 31, height: 31, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  metricLabel: { marginTop: 9, fontSize: 9, fontWeight: '700' },
  metricValue: { marginTop: 2, fontSize: 14, fontWeight: '900', fontVariant: ['tabular-nums'] },
  netCard: { marginTop: 10, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, borderRadius: 19, borderWidth: 1 },
  cardEyebrow: { fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  netValue: { marginTop: 3, fontSize: 18, fontWeight: '900', fontVariant: ['tabular-nums'] },
  deltaBadge: { maxWidth: 130, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 11, alignItems: 'flex-end' },
  deltaText: { fontSize: 10, fontWeight: '900' },
  deltaCaption: { marginTop: 1, fontSize: 7, fontWeight: '600', color: '#8F838F' },
  featureCard: { marginTop: 10, padding: 12, minHeight: 67, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: 18 },
  featureIcon: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  featureCopy: { flex: 1, minWidth: 0 },
  featureTitle: { fontSize: 12, fontWeight: '900' },
  featureText: { marginTop: 3, fontSize: 9, lineHeight: 13, fontWeight: '600' },
  sectionIntro: { marginBottom: 12 },
  sectionTitle: { fontSize: 20, fontWeight: '900', letterSpacing: -0.4 },
  sectionSubtitle: { marginTop: 3, fontSize: 10, lineHeight: 15, fontWeight: '600' },
  budgetHero: { padding: 16, borderRadius: 23, borderWidth: 1 },
  budgetTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  budgetRemaining: { marginTop: 3, fontSize: 25, fontWeight: '900', letterSpacing: -0.7, fontVariant: ['tabular-nums'] },
  budgetPercent: { width: 68, height: 57, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  budgetPercentValue: { fontSize: 17, fontWeight: '900', fontVariant: ['tabular-nums'] },
  budgetPercentLabel: { marginTop: -1, fontSize: 8, fontWeight: '700', color: '#8D7F8F' },
  progressTrack: { height: 9, marginTop: 14, borderRadius: 6, backgroundColor: '#EEE8F1', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 6 },
  budgetStats: { marginTop: 14, paddingTop: 12, flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#EEE5EE' },
  smallStat: { flex: 1, minWidth: 0 },
  smallStatLabel: { fontSize: 8, fontWeight: '700', color: '#948696' },
  smallStatValue: { marginTop: 3, fontSize: 11, fontWeight: '900', color: '#443746', fontVariant: ['tabular-nums'] },
  alertGrid: { marginTop: 10, flexDirection: 'row', gap: 10 },
  alertStat: { flex: 1, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 7, borderRadius: 17, borderWidth: 1 },
  alertValue: { fontSize: 18, fontWeight: '900' },
  alertLabel: { flex: 1, fontSize: 9, fontWeight: '700' },
  infoCard: { marginTop: 10, padding: 13, flexDirection: 'row', alignItems: 'flex-start', gap: 9, borderRadius: 17 },
  infoText: { flex: 1, fontSize: 10, lineHeight: 15, fontWeight: '600' },
  primaryButton: { height: 49, marginTop: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 15, backgroundColor: '#6D4AAF' },
  primaryButtonText: { fontSize: 12, fontWeight: '900', color: '#FFF' },
  fundNetCard: { marginTop: 10, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, borderWidth: 1 },
  fundNetIcon: { width: 47, height: 47, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0EAFE' },
  fundNetValue: { marginTop: 3, fontSize: 20, fontWeight: '900', fontVariant: ['tabular-nums'] },
})
