import { StyleSheet } from 'react-native';

export const PALETTE = {
  bg: '#FFF8FC',
  bgSoft: '#FFF1F8',
  headerStart: '#FFD6EC',
  headerMid: '#E9D5FF',
  headerEnd: '#BFDBFE',
  accent: '#F472B6',
  accentDeep: '#EC4899',
  accentSoft: '#FCE7F3',
  lavender: '#A78BFA',
  lavenderSoft: '#EDE9FE',
  peach: '#FB923C',
  peachSoft: '#FFEDD5',
  text: '#1F2937',
  textMuted: '#6B7280',
  white: '#FFFFFF',
  border: '#F3E8FF',
  shadow: '#C084FC',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PALETTE.bg,
  },
  headerWrap: {
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    marginBottom: 4,
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 22,
  },
  headerDecorCircleLarge: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    top: -24,
    right: -20,
  },
  headerDecorCircleSmall: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    bottom: 18,
    left: 18,
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  content: {
    flex: 1,
    backgroundColor: PALETTE.bg,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginLeft: -8,
  },
  titleContainer: {
    flexDirection: 'column',
    flex: 1,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#7C3AED',
    fontWeight: '600',
    marginTop: 4,
    opacity: 0.85,
  },
  searchSection: {
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 12,
  },
  searchHint: {
    fontSize: 13,
    color: PALETTE.textMuted,
    marginBottom: 10,
    marginLeft: 4,
    fontWeight: '500',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PALETTE.white,
    paddingHorizontal: 14,
    borderRadius: 22,
    minHeight: 56,
    borderWidth: 1.5,
    borderColor: PALETTE.border,
    shadowColor: PALETTE.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  searchIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: PALETTE.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    marginRight: 4,
    fontSize: 15,
    color: PALETTE.text,
    fontWeight: '500',
  },
  clearButton: {
    padding: 4,
    marginRight: 6,
  },
  searchButton: {
    backgroundColor: PALETTE.accent,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    shadowColor: PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  searchButtonText: {
    color: PALETTE.white,
    fontWeight: '800',
    fontSize: 14,
  },
  searchResultCard: {
    backgroundColor: PALETTE.white,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingVertical: 22,
    paddingHorizontal: 20,
    borderRadius: 22,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FBCFE8',
    shadowColor: '#F472B6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 3,
  },
  searchResultName: {
    fontSize: 18,
    fontWeight: '800',
    color: PALETTE.text,
    marginTop: 14,
    textAlign: 'center',
  },
  searchResultEmail: {
    fontSize: 13,
    color: PALETTE.textMuted,
    fontWeight: '500',
    marginTop: 4,
    textAlign: 'center',
  },
  searchResultStk: {
    fontSize: 13,
    color: '#7C3AED',
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
  },
  searchResultAction: {
    marginTop: 16,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 14,
  },
  userTextWrap: {
    flex: 1,
    marginRight: 8,
  },
  userName: {
    fontSize: 16,
    fontWeight: '800',
    color: PALETTE.text,
    marginBottom: 3,
  },
  userEmail: {
    fontSize: 13,
    color: PALETTE.textMuted,
    fontWeight: '500',
  },
  userStk: {
    fontSize: 12,
    color: '#7C3AED',
    fontWeight: '600',
    marginTop: 2,
  },
  sentStatusText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
    marginTop: 3,
  },
  addFriendButton: {
    backgroundColor: PALETTE.lavender,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addFriendText: {
    color: PALETTE.white,
    fontWeight: '800',
    fontSize: 13,
  },
  pendingFriendButton: {
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  pendingFriendText: {
    color: '#4B5563',
    fontWeight: '800',
    fontSize: 13,
  },
  friendStatusButton: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  friendStatusText: {
    color: '#6B7280',
    fontWeight: '800',
    fontSize: 13,
  },
  incomingRequestButton: {
    backgroundColor: PALETTE.peachSoft,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FED7AA',
  },
  incomingRequestText: {
    color: '#C2410C',
    fontWeight: '800',
    fontSize: 13,
  },
  errorCard: {
    backgroundColor: PALETTE.white,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 22,
    borderRadius: 22,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  errorEmoji: {
    fontSize: 34,
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    color: PALETTE.textMuted,
    textAlign: 'center',
    marginBottom: 14,
    lineHeight: 21,
    fontWeight: '500',
  },
  inviteButton: {
    backgroundColor: PALETTE.lavender,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 18,
  },
  inviteText: {
    color: PALETTE.white,
    fontWeight: '800',
    fontSize: 14,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: PALETTE.white,
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 5,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: PALETTE.border,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    flexDirection: 'row',
  },
  activeTab: {
    backgroundColor: PALETTE.accentSoft,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: PALETTE.textMuted,
  },
  activeTabText: {
    color: PALETTE.accentDeep,
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  listItem: {
    backgroundColor: PALETTE.white,
    padding: 16,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#F5F3FF',
    shadowColor: '#DDD6FE',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 2,
  },
  friendSwipeContainer: {
    marginBottom: 12,
  },
  listItemSpaced: {
    marginBottom: 12,
  },
  swipeDeleteActionWrap: {
    width: 88,
    marginLeft: 8,
  },
  swipeDeleteButton: {
    flex: 1,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#EF4444',
  },
  swipeDeleteGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 20,
    minHeight: '100%',
    gap: 6,
  },
  swipeDeleteText: {
    color: PALETTE.white,
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  acceptButton: {
    backgroundColor: PALETTE.accent,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 14,
  },
  rejectButton: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 14,
  },
  acceptText: {
    color: PALETTE.white,
    fontWeight: '800',
    fontSize: 13,
  },
  rejectText: {
    color: '#6B7280',
    fontWeight: '700',
    fontSize: 13,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingTop: 36,
    paddingHorizontal: 24,
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: PALETTE.lavenderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PALETTE.text,
    marginBottom: 6,
    textAlign: 'center',
  },
  emptyText: {
    textAlign: 'center',
    color: PALETTE.textMuted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
  },
  badgeContainer: {
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6,
    paddingHorizontal: 6,
  },
  badgeText: {
    color: 'white',
    fontSize: 11,
    fontWeight: '800',
  },
  sentBadgeContainer: {
    backgroundColor: '#F59E0B',
  },
});
