import { StyleSheet } from 'react-native';
import { FUND_PALETTE } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: FUND_PALETTE.bg,
  },
  header: {
    paddingBottom: 24,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
    marginLeft: -8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  previewCard: {
    marginTop: 22,
    borderRadius: 20,
    overflow: 'hidden',
    minHeight: 150,
  },
  previewCardImageFill: {
    ...StyleSheet.absoluteFillObject,
  },
  previewOverlay: {
    padding: 18,
    minHeight: 150,
    justifyContent: 'flex-end',
  },
  previewThemeTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.25)',
    fontSize: 11,
    fontWeight: '800',
    color: FUND_PALETTE.white,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 10,
    overflow: 'hidden',
  },
  previewName: {
    fontSize: 20,
    fontWeight: '800',
    color: FUND_PALETTE.white,
  },
  previewBalanceLabel: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    marginTop: 16,
  },
  previewBalance: {
    color: FUND_PALETTE.white,
    fontSize: 26,
    fontWeight: '900',
    marginTop: 2,
  },
  previewTarget: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 22,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: FUND_PALETTE.title,
    marginBottom: 10,
    marginTop: 18,
  },
  required: {
    color: FUND_PALETTE.danger,
    fontWeight: '900',
  },
  hint: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
    marginTop: 10,
    lineHeight: 17,
  },
  switchCard: {
    marginTop: 18,
    backgroundColor: FUND_PALETTE.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: FUND_PALETTE.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  switchTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  switchTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: FUND_PALETTE.title,
  },
  switchHint: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
    lineHeight: 17,
    marginTop: 4,
  },
  limitBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEE2E2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  limitBannerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: FUND_PALETTE.danger,
    lineHeight: 18,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FUND_PALETTE.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderWidth: 1.5,
    borderColor: FUND_PALETTE.border,
    gap: 10,
  },
  input: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: FUND_PALETTE.title,
    paddingVertical: 14,
  },
  currency: {
    fontSize: 18,
    fontWeight: '700',
    color: FUND_PALETTE.textMuted,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  chip: {
    backgroundColor: FUND_PALETTE.white,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: FUND_PALETTE.border,
  },
  chipActive: {
    backgroundColor: FUND_PALETTE.primarySoft,
    borderColor: FUND_PALETTE.primary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: FUND_PALETTE.textMuted,
  },
  chipTextActive: {
    color: FUND_PALETTE.primaryDeep,
    fontWeight: '800',
  },
  themeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  themeItem: {
    width: '31%',
    flexGrow: 1,
    maxWidth: '32%',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: FUND_PALETTE.white,
  },
  themeItemActive: {
    borderColor: FUND_PALETTE.primary,
  },
  themeThumb: {
    width: '100%',
    height: 64,
    backgroundColor: FUND_PALETTE.primarySofter,
  },
  themeCheck: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: FUND_PALETTE.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: FUND_PALETTE.textMuted,
    textAlign: 'center',
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  themeLabelActive: {
    color: FUND_PALETTE.primaryDeep,
  },
  infoBox: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: FUND_PALETTE.primarySofter,
    borderRadius: 14,
    padding: 14,
    marginTop: 28,
    alignItems: 'flex-start',
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: FUND_PALETTE.subtitle,
    lineHeight: 19,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 14,
    backgroundColor: FUND_PALETTE.white,
    borderTopWidth: 1,
    borderTopColor: FUND_PALETTE.border,
  },
  submitBtn: {
    backgroundColor: FUND_PALETTE.primary,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: FUND_PALETTE.primaryDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  submitBtnDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
  },
  submitBtnText: {
    color: FUND_PALETTE.white,
    fontSize: 16,
    fontWeight: '800',
  },
});
