import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  // Header matching BudgetScreen / PastelHeaderShell
  headerContent: {
    paddingBottom: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginLeft: -8,
  },
  titleContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#7C3AED',
    fontWeight: '600',
    marginTop: 4,
    opacity: 0.85,
  },
  addButton: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 18,
    backgroundColor: '#EC4899',
    shadowColor: '#EC4899',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  // Scrollable container
  scrollContent: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
    marginBottom: 14,
    letterSpacing: -0.3,
  },
  // Main White Card Container
  mainCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingTop: 4,
    paddingBottom: 24,
    paddingHorizontal: 16,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    minHeight: 380,
  },
  // 2 Tabs: Đang chờ | Đã xong
  tabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: PASTEL_PALETTE.gray100,
    marginBottom: 16,
  },
  tabItem: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    position: 'relative',
  },
  tabItemActive: {},
  tabText: {
    fontSize: 15,
    fontWeight: '600',
    color: PASTEL_PALETTE.textGray,
  },
  tabTextActive: {
    color: PASTEL_PALETTE.title,
    fontWeight: '700',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: -1,
    left: 0,
    right: 0,
    height: 2.5,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 2,
  },
  // Section Headings inside Tab
  sectionHeading: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 12,
  },
  emptySectionText: {
    textAlign: 'center',
    color: PASTEL_PALETTE.textGray,
    fontSize: 14,
    marginVertical: 14,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: PASTEL_PALETTE.gray100,
    marginVertical: 16,
  },
  // Split Bill Card (Matching Cần thu / Cần trả with project colors)
  billCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  billCardPay: {
    borderColor: PASTEL_PALETTE.accentSoft,
  },
  billCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  billCardTopLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    marginRight: 8,
  },
  tagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PASTEL_PALETTE.accentSoft,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    gap: 4,
  },
  tagPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
  billTitleText: {
    fontSize: 14,
    color: PASTEL_PALETTE.textDark,
    fontWeight: '600',
    flex: 1,
  },
  billDateText: {
    fontSize: 12,
    color: PASTEL_PALETTE.textGray,
    marginRight: 6,
  },
  // Card main content row
  billMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
  },
  billMiddleCol: {
    flex: 1,
    marginRight: 10,
  },
  billLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 3,
  },
  billAmountText: {
    fontSize: 13,
    color: PASTEL_PALETTE.textDark,
    marginBottom: 6,
  },
  billAmountBold: {
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  progressTrack: {
    height: 5,
    borderRadius: 2.5,
    backgroundColor: PASTEL_PALETTE.gray200,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 2.5,
  },
  billRightCol: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 88,
    gap: 6,
  },
  statusTextOrange: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#D97706',
    textAlign: 'center',
  },
  statusTextGreen: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#059669',
    textAlign: 'center',
  },
  statusTextMuted: {
    fontSize: 12.5,
    fontWeight: '500',
    color: PASTEL_PALETTE.textGray,
    textAlign: 'center',
  },
  remindOutlineBtn: {
    borderWidth: 1.2,
    borderColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 84,
  },
  remindOutlineBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.accentDeep,
    textAlign: 'center',
  },
  paySolidBtn: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 84,
  },
  paySolidBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  // Empty State
  emptyIllustrationWrap: {
    paddingVertical: 36,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    textAlign: 'center',
    marginTop: 18,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 13.5,
    color: PASTEL_PALETTE.textGray,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
  },
});
