import { StyleSheet } from 'react-native';
import { FUND_PALETTE } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: FUND_PALETTE.bg,
  },
  header: {
    paddingBottom: 24,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
    marginLeft: -8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  amountCard: {
    backgroundColor: FUND_PALETTE.white,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: FUND_PALETTE.border,
  },
  amountLabel: {
    fontSize: 13,
    color: FUND_PALETTE.textMuted,
    fontWeight: '500',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  amountInput: {
    fontSize: 40,
    fontWeight: '900',
    color: FUND_PALETTE.title,
    textAlign: 'center',
    minWidth: 60,
  },
  currency: {
    fontSize: 26,
    fontWeight: '800',
    color: FUND_PALETTE.textMuted,
    marginLeft: 6,
  },
  quickRow: {
    gap: 10,
    marginTop: 18,
    paddingRight: 4,
  },
  quickChip: {
    backgroundColor: FUND_PALETTE.primarySofter,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  quickChipActive: {
    backgroundColor: FUND_PALETTE.primarySoft,
    borderColor: FUND_PALETTE.primary,
  },
  quickChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: FUND_PALETTE.primaryDeep,
  },
  quickChipTextActive: {
    color: FUND_PALETTE.primaryDark,
  },
  minDepositHint: {
    marginTop: 14,
    fontSize: 12,
    fontWeight: '600',
    color: FUND_PALETTE.subtitle,
    textAlign: 'center',
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: FUND_PALETTE.title,
    marginTop: 24,
    marginBottom: 10,
  },
  noteWrap: {
    flexDirection: 'row',
    backgroundColor: FUND_PALETTE.white,
    borderRadius: 16,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: FUND_PALETTE.border,
    minHeight: 60,
  },
  noteInput: {
    flex: 1,
    fontSize: 15,
    color: FUND_PALETTE.title,
    padding: 0,
  },
  securityRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
    alignItems: 'flex-start',
  },
  securityText: {
    flex: 1,
    fontSize: 13,
    color: FUND_PALETTE.textMuted,
    lineHeight: 19,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    backgroundColor: FUND_PALETTE.white,
    borderTopWidth: 1,
    borderTopColor: FUND_PALETTE.border,
    gap: 14,
  },
  footerAmount: {
    flex: 1,
  },
  footerLabel: {
    fontSize: 12,
    color: FUND_PALETTE.textMuted,
  },
  footerValue: {
    fontSize: 18,
    fontWeight: '900',
    color: FUND_PALETTE.title,
    marginTop: 2,
  },
  submitBtn: {
    backgroundColor: FUND_PALETTE.primary,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: FUND_PALETTE.primaryDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  submitBtnDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
  },
  submitBtnText: {
    color: FUND_PALETTE.white,
    fontSize: 16,
    fontWeight: '800',
  },
});
