import { StyleSheet } from 'react-native'
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette'

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  card: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 28,
    padding: 24,
    width: '100%',
    maxHeight: '88%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  headerTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  closeBtn: {
    padding: 6,
    backgroundColor: PASTEL_PALETTE.bg,
    borderRadius: 20,
  },
  hint: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '500',
    lineHeight: 18,
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  charCount: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  charCountLimit: {
    color: PASTEL_PALETTE.accentDeep,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.white,
    paddingHorizontal: 16,
    height: 56,
  },
  amountInputContainerFocused: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  amountInputContainerError: {
    borderColor: '#EF4444',
  },
  amountInputText: {
    flex: 1,
    fontSize: 24,
    fontWeight: '800',
  },
  currencySuffix: {
    fontSize: 18,
    fontWeight: '700',
  },
  selectInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  selectInputError: {
    borderColor: '#EF4444',
  },
  selectedCategory: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  selectedCategoryText: {
    flex: 1,
  },
  smallIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectTextValue: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  selectTextDeleted: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  selectTextPlaceholder: {
    fontSize: 15,
    color: PASTEL_PALETTE.textMuted,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: PASTEL_PALETTE.bg,
    marginBottom: 8,
  },
  inputFocused: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.white,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 15,
    color: PASTEL_PALETTE.textDark,
    fontWeight: '500',
  },
  fieldError: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '600',
    color: '#DC2626',
  },
  primaryBtn: {
    marginTop: 16,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryBtnSpend: {
    backgroundColor: '#DC2626',
  },
  primaryBtnText: {
    color: PASTEL_PALETTE.white,
    fontSize: 16,
    fontWeight: '700',
  },
})
