spring.application.name=Do_An

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/graduation_project_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=270505

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=9090

# JWT Configuration
app.jwt.secret=675A7B6D7A685D7543274F5A643A4F6B735F646A4B7D6C6A435C5F4D3C523A7D
app.jwt.expiration-ms=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranvinhtri2705@gmail.com
spring.mail.password=oqcu vbrq ehlq tgsh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 Client ID
app.google.client-id=your-google-client-id.apps.googleusercontent.com
