import { StyleSheet, Platform } from "react-native";
import Colors from "../../../../shared/constants/Colors";
import { PASTEL_PALETTE } from "../../../../shared/constants/PastelPalette";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  header: {
    paddingBottom: 20,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 6,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: -8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: "900",
    color: PASTEL_PALETTE.title,
    letterSpacing: 0.2,
  },
  sourceFundsCard: {
    backgroundColor: "rgba(255, 255, 255, 0.62)",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.85)",
  },
  sourceFundsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  sourceFundsIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  sourceFundsInfo: {
    flex: 1,
  },
  sourceFundsBalanceWrap: {
    alignItems: "flex-end",
  },
  sourceFundsLabel: {
    color: PASTEL_PALETTE.textMuted,
    fontSize: 13,
    marginBottom: 4,
    fontWeight: "600",
  },
  sourceFundsValue: {
    color: PASTEL_PALETTE.title,
    fontSize: 16,
    fontWeight: "700",
  },
  content: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
  },
  amountSection: {
    marginBottom: 8,
  },
  amountContainer: {
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 18,
    padding: 18,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  amountLabel: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 8,
    fontWeight: "600",
  },
  amountInputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
  },
  amountInput: {
    flex: 1,
    fontSize: 32,
    fontWeight: "700",
    color: PASTEL_PALETTE.title,
    padding: 0,
    margin: 0,
  },
  currencySymbol: {
    fontSize: 24,
    fontWeight: "600",
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
    marginLeft: 4,
  },
  suggestionContainer: {
    flexDirection: "row",
    marginTop: 16,
    gap: 8,
    paddingRight: 4,
  },
  suggestionChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 100,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.accent,
  },
  suggestionChipSelected: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderColor: PASTEL_PALETTE.accentDeep,
  },
  suggestionText: {
    fontSize: 13,
    color: PASTEL_PALETTE.accentDeep,
    fontWeight: "700",
  },
  suggestionTextSelected: {
    color: PASTEL_PALETTE.white,
  },
  paymentSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 16,
  },
  paymentMethodCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.white,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB", // Bọc khung màu xám nhạt cho đẹp
    marginBottom: 12,       // Cách đều nhau
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  paymentIconBg: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: Colors.background,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  paymentInfo: {
    flex: 1,
  },
  paymentTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.text,
    marginBottom: 4,
  },
  paymentSubtitle: {
    fontSize: 13,
    color: Colors.textMuted,
  },
  noteSection: {
    marginBottom: 24,
  },
  noteInputContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: Colors.white,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  noteInput: {
    flex: 1,
    fontSize: 15,
    color: Colors.text,
    minHeight: 40,
    marginLeft: 12,
    textAlignVertical: "top",
  },
  securitySection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PASTEL_PALETTE.accentSoft,
    padding: 16,
    borderRadius: 16,
    marginTop: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  securityIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.white,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  securityText: {
    flex: 1,
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: "500",
    lineHeight: 18,
  },
  categoryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.white,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  categoryCardEmpty: {
    borderStyle: "dashed",
    borderColor: Colors.border,
    backgroundColor: "#FAFAFA",
  },
  categoryIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  categoryIconWrapEmpty: {
    backgroundColor: Colors.border + "55",
  },
  categoryInfo: {
    flex: 1,
    minWidth: 0,
  },
  categoryTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.text,
  },
  categoryTitleEmpty: {
    color: Colors.textMuted,
    fontWeight: "600",
  },
  categoryGroup: {
    fontSize: 13,
    color: Colors.textMuted,
    marginTop: 3,
    fontWeight: "500",
  },
  categoryHint: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 3,
    fontStyle: "italic",
  },
  bankLinkCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: "dashed",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  bankLinkIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.border + "55",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  bankLinkInfo: {
    flex: 1,
    minWidth: 0,
  },
  bankLinkTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.text,
  },
  bankLinkHint: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 8,
    lineHeight: 18,
    fontStyle: "italic",
  },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: "transparent",
  },
  confirmButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    borderRadius: 16, 
    alignItems: "center",
  },
  confirmButtonDisabled: {
    backgroundColor: Colors.border,
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },
  limitSection: {
    marginTop: 0,
  },
  limitToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 4,
  },
  limitToggleTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  limitToggleTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: PASTEL_PALETTE.title,
  },
  limitToggleSummary: {
    fontSize: 11,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: "600",
    marginTop: 3,
  },
  limitDetails: {
    paddingTop: 8,
  },
  limitMeasureWrap: {
    position: "absolute",
    opacity: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  limitRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  limitRowSpacing: {
    marginTop: 12,
  },
  limitLabel: {
    color: PASTEL_PALETTE.textMuted,
    fontSize: 13,
  },
  limitValue: {
    color: PASTEL_PALETTE.title,
    fontSize: 14,
    fontWeight: "600",
  },
  limitPlaceholder: {
    color: PASTEL_PALETTE.lavender,
    fontSize: 13,
    fontStyle: "italic",
  },
  limitDivider: {
    height: 1,
    backgroundColor: PASTEL_PALETTE.border,
    marginHorizontal: -16,
    marginVertical: 12,
  },
  limitStatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  limitStatBlock: {
    flex: 1,
  },
  limitStatBlockEnd: {
    flex: 1,
    alignItems: "flex-end",
  },
  limitStatLabel: {
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 4,
  },
  limitStatValue: {
    fontSize: 14,
    fontWeight: "600",
    color: PASTEL_PALETTE.subtitle,
  },
  limitStatHint: {
    textAlign: "right",
    marginTop: 6,
  },
  limitProgressTrack: {
    height: 6,
    backgroundColor: PASTEL_PALETTE.border,
    borderRadius: 3,
    marginTop: 10,
    overflow: "hidden",
  },
  limitProgressFill: {
    height: "100%",
    borderRadius: 3,
  },
});
