import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '../../../../shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  keyboardWrap: {
    width: '100%',
  },
  modalContainer: {
    backgroundColor: PASTEL_PALETTE.white,
    borderRadius: 28,
    padding: 24,
    shadowColor: PASTEL_PALETTE.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: PASTEL_PALETTE.title,
  },
  closeBtn: {
    padding: 6,
    backgroundColor: PASTEL_PALETTE.bg,
    borderRadius: 20,
  },
  hint: {
    fontSize: 13,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '500',
    lineHeight: 18,
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 8,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  charCount: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
    marginBottom: 0,
  },
  charCountLimit: {
    color: PASTEL_PALETTE.accentDeep,
  },
  amountWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  amountInput: {
    fontSize: 48,
    fontWeight: '800',
    textAlign: 'center',
    minWidth: 50,
  },
  amountSuffix: {
    fontSize: 24,
    fontWeight: '700',
    marginLeft: 4,
    marginTop: 12,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 14,
    backgroundColor: '#FFF',
    paddingHorizontal: 16,
    height: 56,
  },
  amountInputContainerFocused: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  amountInputContainerError: {
    borderColor: '#EF4444',
  },
  amountInputText: {
    flex: 1,
    fontSize: 22,
    fontWeight: 'bold',
    padding: 0,
  },
  currencySuffix: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: PASTEL_PALETTE.bg,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    minHeight: 52,
  },
  inputFocused: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: PASTEL_PALETTE.white,
    shadowColor: PASTEL_PALETTE.accentSoft,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  inputError: {
    borderColor: '#F87171',
  },
  input: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: PASTEL_PALETTE.title,
    paddingVertical: 12,
  },
  error: {
    marginTop: 10,
    fontSize: 12,
    color: '#DC2626',
    fontWeight: '600',
  },
  selectInput: {
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 52,
    backgroundColor: PASTEL_PALETTE.bg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  selectTextPlaceholder: {
    fontSize: 16,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: '500',
  },
  selectTextValue: {
    fontSize: 16,
    color: PASTEL_PALETTE.title,
    fontWeight: '600',
    marginLeft: 10,
  },
  selectedCategory: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtn: {
    marginTop: 32,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryBtnSpend: {
    backgroundColor: '#DC2626',
    shadowColor: '#DC2626',
  },
  primaryBtnText: {
    color: PASTEL_PALETTE.white,
    fontSize: 16,
    fontWeight: '800',
  },
});
