import { StyleSheet } from "react-native";
import Colors from "../../../../shared/constants/Colors";

export const styles = StyleSheet.create({
  cardContainer: {
    width: "100%",
    position: "relative",
  },

  // Main Wallet Body
  walletBody: {
    borderRadius: 24,
    padding: 20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.35)",
    minHeight: 195,
    position: "relative",
  },
  walletStitchBorder: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.35)",
    borderStyle: "dashed",
    borderRadius: 22,
    margin: 5,
    pointerEvents: "none",
  },

  // Slit pocket design
  walletSlit: {
    position: "absolute",
    top: 12,
    left: "5%",
    width: "90%",
    height: 3,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderRadius: 2,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.15)",
  },

  // Wallet flap and button
  walletFlap: {
    position: "absolute",
    top: 0,
    alignSelf: "center",
    width: "55%",
    height: 52,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.35)",
    borderTopWidth: 0,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  walletFlapStitch: {
    position: "absolute",
    top: 0,
    left: 4,
    right: 4,
    bottom: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderStyle: "dashed",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderTopWidth: 0,
  },
  snapButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
    zIndex: 2,
  },
  snapButtonInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  snapDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
  },

  // Content styles
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginTop: 42, // Pushed down to clear the absolute pocket flap
    marginBottom: 12,
  },
  walletName: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.white,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  cardNumber: {
    fontSize: 12,
    fontFamily: "Courier",
    color: "rgba(255, 255, 255, 0.8)",
    marginTop: 4,
    letterSpacing: 1,
  },
  goldFoilBadge: {
    backgroundColor: "rgba(251, 191, 36, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.5)",
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginTop: 6,
  },
  goldFoilText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#FBBF24",
    letterSpacing: 1,
  },
  balanceSection: {
    marginTop: 15,
  },
  balanceLabel: {
    fontSize: 10,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  balanceValue: {
    fontSize: 24,
    fontWeight: "900",
    color: Colors.white,
    marginTop: 4,
  },
  subValue: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.85)",
    fontWeight: "700",
    marginTop: 4,
  },

  // Expanded Wallet Action Tray
  actionsTray: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    borderRadius: 18,
    paddingVertical: 12,
    marginTop: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  actionButton: {
    alignItems: "center",
    flex: 1,
  },
  actionIconBg: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: Colors.white,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: Colors.white,
  },
});
export default styles;
