import { StyleSheet } from "react-native";
import Colors from "../../../../shared/constants/Colors";
import { PASTEL_PALETTE } from "../../../../shared/constants/PastelPalette";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  header: {
    paddingBottom: 18,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
    marginLeft: -8,
  },
  headerSpacer: {
    width: 40,
  },
  headerTitle: {
    flex: 1,
    fontSize: 22,
    fontWeight: "900",
    color: PASTEL_PALETTE.title,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    justifyContent: "center",
  },
  stateBox: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    paddingHorizontal: 24,
  },
  stateText: {
    marginTop: 14,
    fontSize: 15,
    color: PASTEL_PALETTE.textMuted,
    textAlign: "center",
    lineHeight: 22,
  },
  retryButton: {
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: PASTEL_PALETTE.accent,
  },
  retryButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: PASTEL_PALETTE.white,
  },
  cardContainer: {
    width: "100%",
    backgroundColor: Colors.white,
    borderRadius: 28,
    paddingVertical: 28,
    paddingHorizontal: 22,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    shadowColor: PASTEL_PALETTE.lavender,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  brandContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 22,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    paddingLeft: 8,
    paddingRight: 18,
    paddingVertical: 8,
    borderRadius: 100,
    gap: 10,
  },
  brandLogo: {
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.85)",
  },
  brandName: {
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  brandSmart: {
    color: PASTEL_PALETTE.title,
  },
  brandSpend: {
    color: PASTEL_PALETTE.accent,
  },
  qrWrapper: {
    padding: 14,
    backgroundColor: Colors.white,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: PASTEL_PALETTE.border,
    marginBottom: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  qrImage: {
    width: 220,
    height: 240,
  },
  transferBox: {
    width: "100%",
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  transferLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: PASTEL_PALETTE.textMuted,
    letterSpacing: 1,
    marginBottom: 6,
  },
  transferValue: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.text,
    letterSpacing: 1,
  },
  hintBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 18,
    backgroundColor: PASTEL_PALETTE.accentSoft,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  hintIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.white,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  hintText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: PASTEL_PALETTE.textMuted,
    fontWeight: "500",
  },
});
