import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerWrap: {
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    marginBottom: 4,
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 22,
  },
  headerDecorCircleLarge: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    top: -24,
    right: -20,
  },
  headerDecorCircleSmall: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    bottom: 18,
    left: 18,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  leftSection: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginLeft: -8,
  },
  titleContainer: {
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 21,
    fontWeight: "900",
    color: PASTEL_PALETTE.title,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 13,
    color: PASTEL_PALETTE.subtitle,
    marginTop: 2,
    fontWeight: "500",
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  introCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#F4E6F0',
    borderRadius: 20,
    padding: 14,
    marginBottom: 14,
  },
  introIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  introCopy: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  introTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  introText: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
    color: PASTEL_PALETTE.textMuted,
  },
  secureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: '#EAF8F3',
  },
  secureBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#16856A',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#F4E6F0',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  stepBadge: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
  },
  stepText: {
    fontSize: 14,
    fontWeight: '900',
    color: PASTEL_PALETTE.subtitle,
  },
  sectionCopy: {
    flex: 1,
    marginLeft: 11,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  cardSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 13,
    color: PASTEL_PALETTE.textDark,
    marginBottom: 8,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E9DFE8',
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 56,
    fontSize: 16,
    color: PASTEL_PALETTE.title,
    backgroundColor: '#FFFCFE',
  },
  accountInputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  accountInput: {
    paddingRight: 124,
  },
  accountInputActions: {
    position: 'absolute',
    right: 9,
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputActionButton: {
    width: 34,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactsButton: {
    borderRadius: 11,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  scannerButton: {
    marginLeft: 5,
    borderRadius: 11,
    backgroundColor: '#EEE7F7',
  },
  scannerScreen: {
    flex: 1,
    backgroundColor: '#19131C',
  },
  scannerHeader: {
    position: 'absolute',
    zIndex: 2,
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(24, 17, 27, 0.64)',
  },
  scannerClose: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  scannerHeaderCopy: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  scannerHeaderSpacer: {
    width: 42,
  },
  scannerTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#FFF',
  },
  scannerSubtitle: {
    marginTop: 3,
    fontSize: 11,
    color: 'rgba(255,255,255,0.72)',
  },
  scannerBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  scanFrame: {
    width: 254,
    height: 254,
    borderRadius: 28,
  },
  scanCorner: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderColor: '#FFF',
    borderWidth: 4,
  },
  scanCornerTopLeft: {
    top: 0,
    left: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderTopLeftRadius: 22,
  },
  scanCornerTopRight: {
    top: 0,
    right: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderTopRightRadius: 22,
  },
  scanCornerBottomLeft: {
    bottom: 0,
    left: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomLeftRadius: 22,
  },
  scanCornerBottomRight: {
    bottom: 0,
    right: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomRightRadius: 22,
  },
  scanHint: {
    marginTop: 24,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 13,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    color: '#FFF',
    backgroundColor: 'rgba(24,17,27,0.66)',
  },
  scanErrorCard: {
    width: '100%',
    maxWidth: 350,
    marginTop: 22,
    padding: 13,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.96)',
  },
  scanErrorText: {
    flex: 1,
    marginHorizontal: 9,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    color: '#493B4D',
  },
  scanAgainButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#F6E5EC',
  },
  scanAgainText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#C63B58',
  },
  permissionState: {
    flex: 1,
    paddingHorizontal: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF9FC',
  },
  permissionIcon: {
    width: 70,
    height: 70,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEE7F7',
  },
  permissionTitle: {
    marginTop: 17,
    fontSize: 18,
    fontWeight: '900',
    color: '#342938',
  },
  permissionText: {
    marginTop: 8,
    maxWidth: 300,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    color: '#7F7181',
  },
  permissionButton: {
    marginTop: 18,
    paddingHorizontal: 20,
    paddingVertical: 13,
    borderRadius: 14,
    backgroundColor: '#EC4899',
  },
  permissionButtonText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFF',
  },
  inputSuccess: {
    borderColor: '#10B981',
  },
  inputError: {
    borderColor: '#EF4444',
  },
  readOnlyInput: {
    justifyContent: 'center',
    backgroundColor: '#FAF7FB',
    height: 68,
  },
  receiverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  receiverNameText: {
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  receiverPlaceholderText: {
    fontSize: 15,
    color: PASTEL_PALETTE.textMuted,
  },
  receiverErrorText: {
    fontSize: 15,
    color: '#EF4444',
    fontWeight: '600',
  },
  receiverAvatar: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  receiverAvatarText: {
    fontSize: 15,
    fontWeight: '900',
    color: PASTEL_PALETTE.accentDeep,
  },
  receiverCopy: {
    flex: 1,
    minWidth: 0,
  },
  receiverStatusText: {
    marginTop: 2,
    fontSize: 11,
    color: PASTEL_PALETTE.success,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E9DFE8',
    borderRadius: 16,
    backgroundColor: '#FFFCFE',
    paddingHorizontal: 16,
    height: 66,
  },
  amountInput: {
    flex: 1,
    borderWidth: 0,
    backgroundColor: 'transparent',
    padding: 0,
    fontSize: 26,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  currencySuffix: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.accentDeep,
    marginLeft: 8,
  },
  quickAmountRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  quickAmountChip: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 9,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#EEE4ED',
    backgroundColor: '#FFF',
  },
  quickAmountChipSelected: {
    borderColor: PASTEL_PALETTE.accent,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  quickAmountText: {
    fontSize: 12,
    fontWeight: '700',
    color: PASTEL_PALETTE.textMuted,
  },
  quickAmountTextSelected: {
    color: PASTEL_PALETTE.accentDeep,
  },
  amountErrorText: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    color: PASTEL_PALETTE.error,
  },
  transferBalanceCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#FAF7FB',
    borderWidth: 1,
    borderColor: '#EEE4ED',
  },
  transferBalanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  transferBalanceLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  transferBalanceValue: {
    fontSize: 14,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  noteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  noteInput: {
    minHeight: 86,
    height: 86,
    paddingTop: 14,
    lineHeight: 21,
  },
  counterText: {
    marginBottom: 8,
    fontSize: 12,
    fontWeight: '600',
    color: PASTEL_PALETTE.textMuted,
  },
  requiredMark: {
    color: PASTEL_PALETTE.error,
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#F3EAF1',
  },
  saveButton: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 16,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '800',
  },
  saveButtonDisabled: {
    opacity: 0.45,
    shadowOpacity: 0,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  contactsOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'transparent',
  },
  contactsBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  contactsSheet: {
    maxHeight: '72%',
    minHeight: 320,
    paddingHorizontal: 18,
    paddingTop: 10,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: '#EEE4ED',
    shadowColor: '#4C1D5F',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 8,
  },
  contactsHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#E3DCE3',
    marginBottom: 16,
  },
  contactsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  contactsTitle: {
    fontSize: 19,
    fontWeight: '900',
    color: PASTEL_PALETTE.textDark,
  },
  contactsSubtitle: {
    marginTop: 3,
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
  },
  contactsClose: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#F7F2F6',
  },
  contactsList: {
    flexGrow: 0,
  },
  friendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 68,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F2EAF0',
  },
  friendRowDisabled: {
    opacity: 0.48,
  },
  friendCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
  },
  friendName: {
    fontSize: 15,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  friendAccount: {
    marginTop: 4,
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
  },
  contactsState: {
    flex: 1,
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 9,
  },
  contactsStateTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PASTEL_PALETTE.textDark,
  },
  contactsStateText: {
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    color: PASTEL_PALETTE.textMuted,
  },
  retryButton: {
    marginTop: 5,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  retryButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  userNameText: {
    marginTop: 8, 
    fontWeight: '600',
    fontSize: 14
  },
  modalContainer: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: PASTEL_PALETTE.bg,
    borderBottomWidth: 1,
    borderBottomColor: PASTEL_PALETTE.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.title,
  },
  closeButton: {
    padding: 4,
  },
  categoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  categoryLabel: {
    flex: 1,
    fontSize: 15,
    color: PASTEL_PALETTE.title,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: PASTEL_PALETTE.bg,
    borderRadius: 24,
    maxHeight: '80%',
    overflow: 'hidden',
  }
});
