import { StyleSheet } from 'react-native';
import { PASTEL_PALETTE } from '@/shared/constants/PastelPalette';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PASTEL_PALETTE.bg,
  },
  headerWrap: {
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    marginBottom: 4,
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  headerDecorCircleLarge: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    top: -24,
    right: -20,
  },
  headerDecorCircleSmall: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    bottom: 18,
    left: 18,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  leftSection: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginLeft: -8,
  },
  titleContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5B21B6',
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#7C3AED',
    fontWeight: '600',
    marginTop: 4,
    opacity: 0.85,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 18,
  },
  label: {
    fontSize: 14,
    color: PASTEL_PALETTE.subtitle,
    marginBottom: 8,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 54,
    fontSize: 16,
    color: PASTEL_PALETTE.title,
    backgroundColor: '#FFF',
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    borderRadius: 16,
    backgroundColor: '#FFF',
    paddingHorizontal: 16,
    height: 56,
  },
  amountInput: {
    flex: 1,
    borderWidth: 0,
    backgroundColor: 'transparent',
    padding: 0,
    fontSize: 22,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.accentDeep,
  },
  currencySuffix: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.accentDeep,
    marginLeft: 8,
  },
  // Split mode tabs
  modeSelector: {
    flexDirection: 'row',
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
  },
  modeBtnActive: {
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  modeBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: PASTEL_PALETTE.subtitle,
  },
  modeBtnTextActive: {
    color: PASTEL_PALETTE.accentDeep,
    fontWeight: '700',
  },
  // Friend search & list
  searchFriendInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
  },
  friendListWrap: {
    maxHeight: 260,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginBottom: 8,
    backgroundColor: PASTEL_PALETTE.bgSoft,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  friendItemSelected: {
    borderColor: PASTEL_PALETTE.accentDeep,
    backgroundColor: '#F3E8FF',
  },
  friendAvatarCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: PASTEL_PALETTE.lavenderSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  friendAvatarText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PASTEL_PALETTE.accentDeep,
  },
  friendInfo: {
    flex: 1,
  },
  friendName: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  friendEmail: {
    fontSize: 12,
    color: PASTEL_PALETTE.textMuted,
    marginTop: 2,
  },
  friendCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: PASTEL_PALETTE.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  friendCheckboxSelected: {
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderColor: PASTEL_PALETTE.accentDeep,
  },
  friendPickerHint: {
    marginTop: -9,
    marginBottom: 14,
    fontSize: 12,
    lineHeight: 18,
    color: PASTEL_PALETTE.textMuted,
  },
  friendPickerButton: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  friendPickerIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  friendPickerCopy: { flex: 1, minWidth: 0 },
  friendPickerTitle: { fontSize: 14, fontWeight: '800', color: PASTEL_PALETTE.title },
  friendPickerSub: { marginTop: 3, fontSize: 11, fontWeight: '600', color: PASTEL_PALETTE.textMuted },
  selectedFriendsRow: { gap: 8, paddingTop: 12, paddingRight: 4 },
  selectedFriendChip: {
    maxWidth: 180,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingLeft: 4,
    paddingRight: 8,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: PASTEL_PALETTE.accentSoft,
  },
  selectedFriendName: { maxWidth: 98, fontSize: 12, fontWeight: '700', color: PASTEL_PALETTE.title },
  pickerOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'transparent' },
  pickerBackdrop: { ...StyleSheet.absoluteFillObject },
  pickerSheet: {
    height: '84%',
    paddingHorizontal: 18,
    paddingTop: 10,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: PASTEL_PALETTE.white,
  },
  pickerHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#D8D0DF', marginBottom: 14 },
  pickerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  pickerTitle: { fontSize: 20, fontWeight: '900', color: PASTEL_PALETTE.title, letterSpacing: -0.3 },
  pickerSubtitle: { marginTop: 2, fontSize: 12, fontWeight: '600', color: PASTEL_PALETTE.textMuted },
  pickerCloseButton: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: PASTEL_PALETTE.bgSoft },
  pickerSearch: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 13,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: PASTEL_PALETTE.border,
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  pickerSearchInput: { flex: 1, height: '100%', paddingVertical: 0, fontSize: 14, color: PASTEL_PALETTE.title },
  pickerToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, paddingHorizontal: 2 },
  pickerResultCount: { fontSize: 11, fontWeight: '700', color: PASTEL_PALETTE.textMuted },
  pickerSelectAll: { fontSize: 12, fontWeight: '800', color: PASTEL_PALETTE.accentDeep },
  pickerList: { flex: 1 },
  pickerFriendRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 11,
    paddingVertical: 9,
    marginBottom: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: PASTEL_PALETTE.bgSoft,
  },
  pickerFriendRowSelected: { borderColor: PASTEL_PALETTE.accentDeep, backgroundColor: '#F5ECFC' },
  pickerState: { alignItems: 'center', paddingHorizontal: 28, paddingTop: 54 },
  pickerStateTitle: { marginTop: 12, fontSize: 15, fontWeight: '800', color: PASTEL_PALETTE.title },
  pickerStateText: { marginTop: 6, textAlign: 'center', fontSize: 12, lineHeight: 18, color: PASTEL_PALETTE.textMuted },
  pickerDoneButton: { height: 52, marginTop: 10, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: PASTEL_PALETTE.accentDeep },
  pickerDoneText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  // Summary box
  summaryBox: {
    backgroundColor: '#F5F3FF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#DDD6FE',
    marginTop: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: PASTEL_PALETTE.subtitle,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '700',
    color: PASTEL_PALETTE.title,
  },
  perPersonHighlight: {
    fontSize: 18,
    fontWeight: '800',
    color: PASTEL_PALETTE.accentDeep,
  },
  warningBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FCA5A5',
    marginTop: 10,
    gap: 6,
  },
  warningText: {
    fontSize: 13,
    color: '#EF4444',
    fontWeight: '600',
    flex: 1,
  },
  // Footer
  footer: {
    padding: 20,
    paddingBottom: 36,
    backgroundColor: PASTEL_PALETTE.bg,
    flexDirection: 'row',
    gap: 12,
  },
  backBtnFooter: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: PASTEL_PALETTE.border,
  },
  submitBtnFooter: {
    flex: 2,
    backgroundColor: PASTEL_PALETTE.accentDeep,
    borderRadius: 20,
    padding: 18,
    alignItems: 'center',
    shadowColor: PASTEL_PALETTE.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  backBtnText: {
    color: PASTEL_PALETTE.title,
    fontSize: 16,
    fontWeight: '600',
  },
});
